/**
 * Structured logging with Pino.
 * Owns: JSON structured logging configuration, log output formatting.
 * Does NOT own: business logic. Request IDs are generated by requestId middleware.
 *
 * Usage:
 *   const logger = require('./logger');
 *   logger.info({ msg: 'Operation started', operation: 'user.register', userId });
 *   logger.error({ msg: 'Database error', error: err.message, query });
 *
 * Each log should include:
 *   - msg: human-readable message
 *   - operation: what operation (e.g. 'user.register', 'db.query')
 *   - Any relevant context (userId, itemId, error, etc.)
 */

const pino = require('pino');

// Determine environment
const isProduction = process.env.NODE_ENV === 'production';

// Build transport config for pretty-printing in development
let transport = undefined;
if (!isProduction) {
  try {
    transport = {
      target: 'pino-pretty',
      options: {
        colorize: true,
        translateTime: 'SYS:standard',
        ignore: 'pid,hostname',
        singleLine: false,
      },
    };
  } catch (err) {
    // pino-pretty not available in production build
  }
}

// Initialize Pino logger
const logger = pino({
  level: (process.env.LOG_LEVEL || (isProduction ? 'info' : 'debug')).toLowerCase(),
  // Pretty-print JSON in development, keep JSON in production
  transport,
  // Always include timestamp
  timestamp: pino.stdTimeFunctions.isoTime,
});

module.exports = logger;
