/**
 * Auth routes.
 * Owns: login, register, logout, token refresh, password reset, email verification.
 * Does NOT own: child schedule, family settings, push notifications.
 */
const express = require('express');
const jwt = require('jsonwebtoken');
const { v4: uuidv4 } = require('uuid');
const { hashPassword, comparePassword } = require('../../lib/hash');
const db = require('../../lib/db');
const config = require('../../lib/config');
const { loginLimiter, registrationLimiter } = require('../../middleware/rateLimiter');
const { getParentRoles, getChildrenForParent, syncAccountType } = require('../../../db/parent-access');
const { recordLoginEvent } = require('../../lib/login-event');
const { isEmailAllowlisted, familyHasMagicViewAccess } = require('../../lib/magic-view-access');
const { requireAuth } = require('../../middleware/auth');
const { generateCsrfToken } = require('../../middleware/csrf');
const {
  createRefreshToken,
  revokeRefreshToken,
  setRefreshCookie,
  setAccessCookie,
} = require('../../lib/refresh-tokens');
const parentPinDb = require('../../../db/parent-pin');
const {
  sendVerificationEmail,
  registerContact,
} = require('../../lib/email');
const { sendWelcomeEmail } = require('../../lib/welcome-mailer');
const { createNewsletterSubscription } = require('../../lib/newsletter-subscribe');
const familySubscriptions = require('../../../db/family-subscriptions');
const { validate } = require('../../middleware/validate');
const {
  RegisterSchema,
  LoginSchema,
} = require('../../lib/schemas');

const router = express.Router();

const { parseDuration, clearAllSessionCookies } = require('./session');

// ─── POST /api/auth/register ──────────────────────────────
router.post('/register', registrationLimiter, validate(RegisterSchema), async (req, res) => {
  try {
    // Registration is always open. Only maintenance mode blocks new signups.
    try {
      const result = await db.query("SELECT enabled FROM feature_flag WHERE key = 'maintenance_mode' LIMIT 1");
      if (result.rows.length > 0 && result.rows[0].enabled) {
        return res.status(403).json({ error: 'Registrering är för närvarande stängd' });
      }
    } catch (flagErr) {
      console.error('[AUTH] Feature flag check error:', flagErr);
    }

    const { email, password, name, family_name } = req.body;

    if (!email || !password) {
      return res.status(400).json({ error: 'E-post och lösenord krävs' });
    }
    if (typeof email !== 'string' || !email.includes('@')) {
      return res.status(400).json({ error: 'Ogiltig e-postadress' });
    }
    if (password.length < 8) {
      return res.status(400).json({ error: 'Lösenordet måste vara minst 8 tecken' });
    }

    // Validate name — required for auto-generating family name
    if (!name || typeof name !== 'string' || name.trim().length < 1) {
      return res.status(400).json({ error: 'Namn krävs för att skapa ett familjkonto' });
    }
    const trimmedName = name.trim();
    const isFamilyNameAutoGenerated = !family_name || family_name.trim() === '';
    const finalFamilyName = isFamilyNameAutoGenerated
      ? `${trimmedName}s familj`
      : family_name.trim();

    const normalizedEmail = email.toLowerCase().trim();

    // Check if email exists
    const existing = await db.query(
      'SELECT id FROM parent WHERE LOWER(email) = $1',
      [normalizedEmail]
    );
    if (existing.rows.length > 0) {
      return res.status(409).json({ error: 'Det finns redan ett konto med den e-postadressen' });
    }

    const passwordHash = await hashPassword(password);
    const client = await db.getClient();

    try {
      await client.query('BEGIN');

      // Determine is_lifetime_free: first N families (admin founder limit) get it automatically.
      // Count + insert in same transaction to prevent race condition.
      // Families beyond #200 require a paid subscription.
      const countResult = await client.query('SELECT COUNT(*)::int AS count FROM family');
      const familyCount = countResult.rows[0].count;
      const { getFounderFamilyLimitWithClient, qualifiesForLifetimeFree } = require('../../lib/payment-policy');
      const founderLimit = await getFounderFamilyLimitWithClient(client);
      const isLifetimeFree = qualifiesForLifetimeFree(familyCount, founderLimit);

      // Create family — subscription_status defaults to 'none' (CHECK constraint).
      // Trial access is tracked via trial_ends_at + family_subscriptions table.
      const familyResult = await client.query(
        `INSERT INTO family (name, subscription_status, trial_ends_at, is_lifetime_free)
         VALUES ($1, 'none', NOW() + INTERVAL '14 days', $2)
         RETURNING id`,
        [finalFamilyName, isLifetimeFree]
      );
      const familyId = familyResult.rows[0].id;

      console.log(`[AUTH] Family #${familyCount + 1} created — lifetime_free: ${isLifetimeFree} (limit ${founderLimit})`);

      // New parents always start unverified. They get a 24h grace period to log in
      // while they verify their email. After 24h, login is blocked until verified.
      // Newsletter subscription is auto-opt-in (newsletter_subscribed = true).
      const parentResult = await client.query(
        `INSERT INTO parent (family_id, email, password_hash, name, verified, newsletter_subscribed, family_role, onboarding_completed)
         VALUES ($1, $2, $3, $4, false, true, $5, false) RETURNING id`,
        [familyId, normalizedEmail, passwordHash, trimmedName, 'förälder']
      );
      const parentId = parentResult.rows[0].id;

      // Load admin-defined default templates (falls back to hardcoded if table doesn't exist yet).
      // Include schema_type so each template is tagged for age-based filtering during child creation.
      let defaultActivities;
      try {
        const tplResult = await client.query(
          `SELECT name, icon, category_name, star_value, sort_order, schema_type
           FROM default_activity_template ORDER BY schema_type ASC, category_name ASC, sort_order ASC`
        );
        defaultActivities = tplResult.rows.length > 0
          ? tplResult.rows.map(r => ({ name: r.name, icon: r.icon, category: r.category_name, star_value: r.star_value, sort_order: r.sort_order, schema_type: r.schema_type || 'forskola' }))
          : null;
      } catch {
        defaultActivities = null; // table doesn't exist yet
      }

      if (!defaultActivities) {
        defaultActivities = [
          // Förskola defaults (ages 2-5)
          { name: 'Vakna',                   icon: '🛏️', category: 'Morgon',      star_value: 1, sort_order: 0, schema_type: 'forskola' },
          { name: 'Klä på sig',              icon: '🌟', category: 'Morgon',      star_value: 1, sort_order: 1, schema_type: 'forskola' },
          { name: 'Borsta tänderna',          icon: '🪥', category: 'Morgon',      star_value: 1, sort_order: 2, schema_type: 'forskola' },
          { name: 'Äta frukost',             icon: '🍳', category: 'Morgon',      star_value: 1, sort_order: 3, schema_type: 'forskola' },
          { name: 'Förskola/Skola',          icon: '🏫', category: 'Förmiddag',   star_value: 1, sort_order: 0, schema_type: 'forskola' },
          { name: 'Leka ute',                icon: '🛝', category: 'Förmiddag',   star_value: 1, sort_order: 1, schema_type: 'forskola' },
          { name: 'Pyssel',                  icon: '🎨', category: 'Förmiddag',   star_value: 1, sort_order: 2, schema_type: 'forskola' },
          { name: 'Mellanmål',               icon: '🍎', category: 'Eftermiddag', star_value: 1, sort_order: 0, schema_type: 'forskola' },
          { name: 'Leka',                    icon: '🧩', category: 'Eftermiddag', star_value: 1, sort_order: 1, schema_type: 'forskola' },
          { name: 'Träning/Aktivitet',       icon: '🏃', category: 'Eftermiddag', star_value: 1, sort_order: 2, schema_type: 'forskola' },
          { name: 'Middag',                  icon: '🍽️', category: 'Kväll',       star_value: 1, sort_order: 0, schema_type: 'forskola' },
          { name: 'Borsta tänderna (kväll)',  icon: '🪥', category: 'Kväll',       star_value: 1, sort_order: 1, schema_type: 'forskola' },
          { name: 'Pyjamas',                 icon: '🧸', category: 'Kväll',       star_value: 1, sort_order: 2, schema_type: 'forskola' },
          { name: 'Godnattsaga',             icon: '📕', category: 'Kväll',       star_value: 1, sort_order: 3, schema_type: 'forskola' },
          { name: 'Sova',                    icon: '😴', category: 'Kväll',       star_value: 1, sort_order: 4, schema_type: 'forskola' },
          // Skola defaults (ages 6+)
          { name: 'Vakna & klä på sig',      icon: '🌅', category: 'Morgon',      star_value: 1, sort_order: 0, schema_type: 'skola' },
          { name: 'Frukost',                 icon: '🥣', category: 'Morgon',      star_value: 1, sort_order: 1, schema_type: 'skola' },
          { name: 'Borsta tänderna',          icon: '🪥', category: 'Morgon',      star_value: 1, sort_order: 2, schema_type: 'skola' },
          { name: 'Packa skolväska',          icon: '🎒', category: 'Morgon',      star_value: 1, sort_order: 3, schema_type: 'skola' },
          { name: 'Skola',                   icon: '🏫', category: 'Förmiddag',   star_value: 2, sort_order: 0, schema_type: 'skola' },
          { name: 'Rast & lek',              icon: '⚽', category: 'Förmiddag',   star_value: 1, sort_order: 1, schema_type: 'skola' },
          { name: 'Mellanmål',               icon: '🍎', category: 'Eftermiddag', star_value: 1, sort_order: 0, schema_type: 'skola' },
          { name: 'Läxor',                   icon: '📚', category: 'Eftermiddag', star_value: 2, sort_order: 1, schema_type: 'skola' },
          { name: 'Fritidsaktivitet',         icon: '🏃', category: 'Eftermiddag', star_value: 2, sort_order: 2, schema_type: 'skola' },
          { name: 'Middag',                  icon: '🍽️', category: 'Kväll',       star_value: 1, sort_order: 0, schema_type: 'skola' },
          { name: 'Borsta tänderna (kväll)',  icon: '🪥', category: 'Kväll',       star_value: 1, sort_order: 1, schema_type: 'skola' },
          { name: 'Läsa',                    icon: '📖', category: 'Kväll',       star_value: 1, sort_order: 2, schema_type: 'skola' },
          { name: 'Sova',                    icon: '😴', category: 'Kväll',       star_value: 1, sort_order: 3, schema_type: 'skola' },
        ];
      }

      // Create SIX template categories: Förskola, Skola, Morgon, Dag, Kväll, Helg
      // Each category corresponds to a standard template group that parents can customize.
      const TEMPLATE_CATEGORIES = [
        { key: 'forskola', name: 'Förskola', sort_order: 0 },
        { key: 'skola',    name: 'Skola',    sort_order: 1 },
        { key: 'morgon',   name: 'Morgon',   sort_order: 2 },
        { key: 'dag',      name: 'Dag',      sort_order: 3 },
        { key: 'kvall',    name: 'Kväll',    sort_order: 4 },
        { key: 'helg',     name: 'Helg',     sort_order: 5 },
      ];
      // Time-of-day sort multipliers to preserve ordering within each category:
      const TIME_CATEGORY_OFFSET = { 'Morgon': 0, 'Förmiddag': 100, 'Eftermiddag': 200, 'Kväll': 300 };
      // Map category_name to time_group
      const CATEGORY_TO_TIME_GROUP = {
        'Morgon': 'morgon', 'Förmiddag': 'formiddag',
        'Eftermiddag': 'eftermiddag', 'Kväll': 'kvall',
      };

      // Create all 6 categories
      const categoryMap = {};
      for (const cat of TEMPLATE_CATEGORIES) {
        const catResult = await client.query(
          'INSERT INTO category (family_id, name, sort_order, is_default) VALUES ($1, $2, $3, true) RETURNING id',
          [familyId, cat.name, cat.sort_order]
        );
        categoryMap[cat.key] = catResult.rows[0].id;
      }

      // Seed activities from default_activity_template using template_group.
      // Migration 050 cleared template_group/schema_type to NULL — filter those out
      // and fall back to hardcoded defaults if no grouped activities remain.
      let groupedActivities;
      try {
        const grpResult = await client.query(
          `SELECT name, icon, category_name, star_value, sort_order, sub_steps,
                  COALESCE(template_group, schema_type) AS grp
           FROM default_activity_template
           WHERE COALESCE(template_group, schema_type) IS NOT NULL
           ORDER BY grp, category_name, sort_order ASC`
        );
        groupedActivities = grpResult.rows.length > 0 ? grpResult.rows : null;
      } catch {
        groupedActivities = null;
      }

      if (groupedActivities) {
        for (const act of groupedActivities) {
          const catId = categoryMap[act.grp];
          if (!catId) continue; // skip unknown groups
          const timeGroup = CATEGORY_TO_TIME_GROUP[act.category_name] || 'morgon';
          const timeOffset = TIME_CATEGORY_OFFSET[act.category_name] ?? 400;
          const combinedSort = timeOffset + (act.sort_order ?? 0);
          const tplResult = await client.query(
            'INSERT INTO activity_template (family_id, name, icon, category_id, star_value, is_favorite, time_group, schema_type, sort_order) VALUES ($1, $2, $3, $4, $5, false, $6, $7, $8) RETURNING id',
            [familyId, act.name, act.icon, catId, act.star_value, timeGroup, act.grp, combinedSort]
          );

          // Create sub-steps from default_activity_template.sub_steps JSONB
          const subSteps = act.sub_steps || [];
          if (Array.isArray(subSteps) && subSteps.length > 0) {
            for (let si = 0; si < subSteps.length; si++) {
              await client.query(
                `INSERT INTO activity_sub_step (activity_template_id, name, icon, sort_order)
                 VALUES ($1, $2, $3, $4)`,
                [tplResult.rows[0].id, subSteps[si].name, subSteps[si].icon || null, si]
              );
            }
          }
        }
      } else {
        // Fallback: seed from hardcoded defaults into forskola/skola categories only
        for (const act of defaultActivities) {
          const catId = categoryMap[act.schema_type];
          if (!catId) continue;
          const timeGroup = CATEGORY_TO_TIME_GROUP[act.category] || 'morgon';
          const timeOffset = TIME_CATEGORY_OFFSET[act.category] ?? 400;
          const combinedSort = timeOffset + (act.sort_order ?? 0);
          await client.query(
            'INSERT INTO activity_template (family_id, name, icon, category_id, star_value, is_favorite, time_group, schema_type, sort_order) VALUES ($1, $2, $3, $4, $5, false, $6, $7, $8)',
            [familyId, act.name, act.icon, catId, act.star_value, timeGroup, act.schema_type, combinedSort]
          );
        }
      }

      // Seed default rewards from admin-defined library (fail-open: no default rewards if table missing)
      try {
        const defaultRewards = await client.query(
          'SELECT id, name, icon, star_cost FROM default_reward ORDER BY sort_order ASC, star_cost ASC'
        );
        for (const r of defaultRewards.rows) {
          await client.query(
            `INSERT INTO reward (family_id, name, icon, star_cost, requires_approval, is_active, source_default_id, modified_by_family)
             VALUES ($1, $2, $3, $4, false, true, $5, false)`,
            [familyId, r.name, r.icon, r.star_cost, r.id]
          );
        }
      } catch {
        // Table doesn't exist yet (pre-migration) — skip silently
      }

      // Standard schedules are NOT seeded as family templates.
      // Parents browse the standard library (live admin data) and explicitly copy to children.
      // "Mina scheman" stays empty until the parent creates their own templates.

      // Create notification preferences
      await client.query(
        'INSERT INTO notification_preference (parent_id) VALUES ($1)',
        [parentId]
      );

      // Create verification token inside the transaction so it's atomic with user creation.
      // WHY: if this fails after COMMIT, the user exists but has no token — unrecoverable
      // without the resend endpoint.
      const verifyToken = uuidv4();
      await client.query(
        'INSERT INTO email_verification (parent_id, token, expires_at) VALUES ($1, $2, $3)',
        [parentId, verifyToken, new Date(Date.now() + config.verification.tokenExpiryHours * 3600_000)]
      );

      await createNewsletterSubscription(client, parentId, normalizedEmail);

      // Create component-based subscription (14-day trial + basic_app)
      await client.query(
        `INSERT INTO family_subscriptions (family_id, tier, trial_expires_at, components)
         VALUES ($1, 'trial', NOW() + INTERVAL '14 days', $2)`,
        [
          familyId,
          JSON.stringify([{ component: 'basic_app', granted_at: new Date().toISOString(), expires_at: null }]),
        ]
      );

      await client.query('COMMIT');

      // Analytics: funnel step — signup_started (family just created)
      require('../../lib/analytics-tracker').trackSignupStarted(familyId);

      // Register contact (no-op with Resend — kept for compatibility)
      try {
        await registerContact(normalizedEmail, trimmedName, 'signup');
      } catch (err) {
        console.error('[AUTH] registerContact failed for', normalizedEmail, ':', err.message);
      }

      // Send verification email (blocking so errors are surfaced immediately)
      try {
        await sendVerificationEmail(normalizedEmail, verifyToken);
      } catch (err) {
        console.error('[AUTH] sendVerificationEmail FAILED for', normalizedEmail, ':', err.message);
        // Don't block HTTP response — user can still log in and request resend
      }

      // Send welcome email (fire-and-forget — don't block registration response)
      // Gate 2J: valkomstmail — only send if feature is live/dev for this family
      const { hasAccess } = require('../../../db/features');
      const welcomeEmailAllowed = await hasAccess(familyId, 'valkomstmail');
      if (welcomeEmailAllowed) {
        sendWelcomeEmail(normalizedEmail, parentId, {
          foralderns_namn: trimmedName,
          barnets_namn: '',
        }).catch(err => {
          console.error('[AUTH] Welcome email send failed:', err.message);
        });
      }

      res.status(201).json({
        message: 'Konto skapat! Kontrollera din e-post för att verifiera ditt konto.',
        parentId,
        family_name: finalFamilyName,
        is_family_name_auto_generated: isFamilyNameAutoGenerated,
        parent_name: trimmedName,
        ...(process.env.NODE_ENV !== 'production' && { verifyToken }),
      });
    } catch (err) {
      await client.query('ROLLBACK');
      throw err;
    } finally {
      client.release();
    }
  } catch (err) {
    console.error('[AUTH] Register error:', err);
    res.status(500).json({ error: 'Något gick fel. Försök igen senare.' });
  }
});

// ─── POST /api/auth/login ─────────────────────────────────
router.post('/login', loginLimiter, validate(LoginSchema), async (req, res) => {
  try {
    const { email, password } = req.body;
    if (!email || !password) {
      return res.status(400).json({ error: 'E-post och lösenord krävs' });
    }

    const normalizedEmail = email.toLowerCase().trim();
    const result = await db.query(
      'SELECT id, family_id, email, password_hash, verified, is_admin, created_at, COALESCE(locked, false) as locked, COALESCE(onboarding_completed, true) as onboarding_completed FROM parent WHERE LOWER(email) = $1',
      [normalizedEmail]
    );

    // Log attempt
    await db.query(
      'INSERT INTO login_attempt (identifier, ip_address, success) VALUES ($1, $2, $3)',
      [normalizedEmail, req.ip || 'unknown', false]
    );

    const parent = result.rows[0];
    if (!parent || !(await comparePassword(password, parent.password_hash))) {
      return res.status(401).json({ error: 'Felaktig e-post eller lösenord' });
    }

    if (parent.locked) {
      return res.status(403).json({ error: 'Ditt konto har spärrats. Kontakta administratören.' });
    }

    // Email verification with 24h grace period.
    // New registrations can log in freely for 24h without verifying.
    // After that, verification is enforced.
    if (!parent.verified) {
      const createdAt = new Date(parent.created_at);
      const gracePeriodMs = 24 * 60 * 60 * 1000;
      const graceDeadline = new Date(createdAt.getTime() + gracePeriodMs);
      const now = new Date();

      if (now > graceDeadline) {
        return res.status(403).json({
          error: 'Du måste verifiera din e-postadress för att fortsätta',
          code: 'EMAIL_VERIFICATION_REQUIRED',
          email: normalizedEmail,
        });
      }
      // Within grace period — allow login but include verification status
    }

    // Mark attempt as success
    await db.query(
      `UPDATE login_attempt SET success = true
       WHERE identifier = $1 AND created_at >= NOW() - INTERVAL '1 second'`,
      [normalizedEmail]
    );

    // Record login event for analytics
    const loginRole = parent.is_admin ? 'admin' : 'parent';
    recordLoginEvent({ userId: parent.id, role: loginRole, familyId: parent.family_id }).catch(() => {});

    const accessToken = jwt.sign(
      {
        id: parent.id,
        type: 'parent',
        familyId: parent.family_id,
        email: parent.email,
        isAdmin: parent.is_admin,
      },
      config.jwt.secret,
      { expiresIn: config.jwt.expiresIn }
    );

    // Issue 7-day refresh token (stored hashed in DB, raw value in httpOnly cookie)
    const rawRefresh = await createRefreshToken({
      userId: parent.id,
      userType: 'parent',
      familyId: parent.family_id,
    });
    setRefreshCookie(res, rawRefresh);

    // Set access token as httpOnly cookie — XSS cannot read it.
    // Cookie maxAge matches JWT TTL so they expire together.
    const expiresInSecs = typeof config.jwt.expiresIn === 'string'
      ? parseDuration(config.jwt.expiresIn)
      : config.jwt.expiresIn;
    setAccessCookie(res, accessToken, expiresInSecs);

    // Issue fresh CSRF token for the new session
    const csrfToken = generateCsrfToken(res);

    const user = {
      id: parent.id,
      email: parent.email,
      familyId: parent.family_id,
      isAdmin: parent.is_admin,
      type: 'parent',
      onboarding_completed: parent.onboarding_completed,
    };

    // expiresAt lets the frontend schedule proactive silent refresh
    // (the access token itself is in an httpOnly cookie — JS can't decode it)
    const expiresAt = Date.now() + expiresInSecs * 1000;
    res.json({ csrfToken, user, expiresAt });
  } catch (err) {
    console.error('[AUTH] Login error:', err);
    res.status(500).json({ error: 'Något gick fel. Försök igen senare.' });
  }
});

// ─── POST /api/auth/me/preferences ───────────────────────
// Update parent's preferred_view_mode. Only parents with active pedagog children can switch to 'pedagog'.
router.post('/me/preferences', requireAuth, async (req, res) => {
  try {
    if (req.user.type !== 'parent') {
      return res.status(400).json({ error: 'Endast föräldrar kan uppdatera visningsläge' });
    }
    const { preferredViewMode } = req.body || {};
    if (!preferredViewMode || !['parent', 'pedagog'].includes(preferredViewMode)) {
      return res.status(400).json({ error: 'preferredViewMode must be "parent" or "pedagog"' });
    }
    if (preferredViewMode === 'pedagog') {
      const roles = await getParentRoles(req.user.id);
      if (roles.pedagogChildIds.length === 0) {
        return res.status(400).json({ error: 'NO_PEDAGOG_ACCESS' });
      }
    }
    await db.query(
      'UPDATE parent SET preferred_view_mode = $2 WHERE id = $1',
      [req.user.id, preferredViewMode]
    );
    res.json({ success: true });
  } catch (err) {
    console.error('[AUTH] me/preferences error:', err);
    res.status(500).json({ error: 'Kunde inte spara inställningar' });
  }
});

// ─── GET /api/auth/me ─────────────────────────────────────
router.get('/me', requireAuth, async (req, res) => {
  try {
    if (req.user.type === 'parent') {
      const parentResult = await db.query(
        `SELECT p.id, p.email, p.family_id, p.is_admin, p.verified, p.created_at,
                COALESCE(p.onboarding_completed, true) as onboarding_completed,
                COALESCE(p.account_type, 'family') as account_type,
                COALESCE(p.preferred_view_mode, 'parent') as preferred_view_mode,
                f.is_lifetime_free,
                p.password_hash IS NOT NULL AS has_password,
                p.apple_user_id IS NOT NULL AS has_apple_linked,
                p.apple_email
         FROM parent p
         JOIN family f ON f.id = p.family_id
         WHERE p.id = $1`,
        [req.user.id]
      );
      if (parentResult.rows.length === 0) {
        return res.status(404).json({ error: 'Användare hittades inte' });
      }

      const parent = parentResult.rows[0];

      // Get parent roles (primary/shared vs pedagog-only)
      const roles = await getParentRoles(req.user.id);
      const hasPedagogChildren = roles.pedagogChildIds.length > 0;
      const isDualRole = roles.isDualRole;

      // Determine effective view mode — fallback to 'parent' if set to 'pedagog'
      // but no pedagog children remain (e.g., all pedagogen children unlinked)
      let effectiveViewMode = parent.preferred_view_mode;
      if (effectiveViewMode === 'pedagog' && roles.pedagogChildIds.length === 0) {
        effectiveViewMode = 'parent';
        // Sync account_type since pedagogen-only children are gone
        if (parent.account_type === 'educator') {
          await syncAccountType(req.user.id);
        }
      }

      // Get children via getChildrenForParent (revoked_at filtering applied there)
      const children = await getChildrenForParent(req.user.id, { allowedRoles: ['primary', 'shared'] });
      // Strip sensitive fields before sending to client
      for (const child of children) {
        delete child.pin;
        delete child.pin_fingerprint;
        delete child.pin_hint;
        delete child.pin_is_set;
      }

      return res.json({
        ...parent,
        isAdmin: !!parent.is_admin,
        magic_view_enabled: isEmailAllowlisted(parent.email),
        account_type: parent.account_type,
        preferred_view_mode: effectiveViewMode,
        hasPedagogChildren,
        isDualRole,
        is_lifetime_free: parent.is_lifetime_free,
        accountAuth: {
          hasPassword: parent.has_password,
          hasAppleLinked: parent.has_apple_linked,
          email: parent.email,
          appleEmail: parent.apple_email || null,
          canUnlinkApple: parent.has_password && parent.has_apple_linked,
        },
        children,
      });
    }

    if (req.user.type === 'child') {
      const childResult = await db.query(
        `SELECT id, name, emoji, avatar_url, family_id, username, view_mode, timezone, birthday, created_at
         FROM child WHERE id = $1`,
        [req.user.id]
      );
      if (childResult.rows.length === 0) {
        return res.status(404).json({ error: 'Användare hittades inte' });
      }

      const child = childResult.rows[0];
      const magicViewEnabled = await familyHasMagicViewAccess(child.family_id);

      return res.json({ ...child, type: 'child', magic_view_enabled: magicViewEnabled });
    }

    res.status(400).json({ error: 'Okänd användartyp' });
  } catch (err) {
    console.error('[AUTH] Me error:', err);
    res.status(500).json({ error: 'Något gick fel. Försök igen senare.' });
  }
});

// ─── GET /api/auth/login-picker-children ───────────────────
// Barnväljare: barn i familjen (namn + avatar) utan att aktivera vuxensession i klienten.
// Response: { hasSession, children[], parent? } — parent enables add-child onboarding without full re-login.
router.get('/login-picker-children', async (req, res) => {
  try {
    const { resolveParentIdForLoginPicker } = require('../../middleware/auth');
    const parentId = resolveParentIdForLoginPicker(req);
    if (!parentId) {
      return res.json({ hasSession: false, children: [] });
    }

    const parentResult = await db.query(
      `SELECT id, email, family_id, is_admin, onboarding_completed
       FROM parent WHERE id = $1`,
      [parentId]
    );
    const parentRow = parentResult.rows[0];
    if (!parentRow) {
      return res.json({ hasSession: false, children: [] });
    }

    const children = await getChildrenForParent(parentId, { allowedRoles: ['primary', 'shared'] });
    res.json({
      hasSession: true,
      children: children.map((c) => ({
        username: c.username,
        name: c.name,
        emoji: c.emoji || '⭐',
        avatar_url: c.avatar_url || null,
        familyId: c.family_id || null,
      })),
      parent: {
        id: parentRow.id,
        email: parentRow.email || null,
        familyId: parentRow.family_id,
        isAdmin: parentRow.is_admin || false,
        type: 'parent',
        onboarding_completed: parentRow.onboarding_completed,
      },
    });
  } catch (err) {
    console.error('[AUTH] login-picker-children error:', err.message);
    res.status(500).json({ error: 'Något gick fel. Försök igen senare.' });
  }
});

// ─── POST /api/auth/logout ────────────────────────────────
// Revoke the refresh token and clear cookies.
// When a child logs out, if a parent session was saved (via stjarndag_parent_session),
// restore it so the parent remains logged in.
// Body { switchChild: true } — end child session only; keep parent session cookie for barnväljare.

router.post('/logout', async (req, res) => {
  try {
    const switchChild = req.body?.switchChild === true;
    const raw = req.cookies?.refresh_token;
    const accessTokenStr = req.cookies?.access_token;
    const decoded = accessTokenStr ? jwt.decode(accessTokenStr) : null;

    if (raw) {
      await revokeRefreshToken(raw);
    }
    clearAllSessionCookies(res);

    // ── Byt barn: end child JWT only; keep stjarndag_parent_session for barnväljare ──
    if (switchChild && decoded?.type === 'child') {
      return res.json({ message: 'Utloggad', switchChild: true });
    }

    // ── Restore parent session only if CHILD is logging out ────────────────
    if (decoded?.type !== 'child') {
      res.clearCookie('stjarndag_parent_session', { path: '/' });
      return res.json({ message: 'Utloggad' });
    }

    const parentSessionCookie = req.cookies?.stjarndag_parent_session;
    if (parentSessionCookie) {
      let session;
      try {
        session = JSON.parse(Buffer.from(parentSessionCookie, 'base64').toString('utf8'));
      } catch {
        // Invalid cookie — just clear it
        res.clearCookie('stjarndag_parent_session', { path: '/' });
        return res.json({ message: 'Utloggad' });
      }

      if (session?.access_token && session?.refresh_token) {
        // Require PIN if the saved parent account has one set.
        try {
          let savedParentId = null;
          try {
            const parentDecoded = jwt.decode(session.access_token);
            if (parentDecoded?.type === 'parent') savedParentId = parentDecoded.id;
          } catch { /* fall through */ }

          const needsPin = savedParentId
            ? await parentPinDb.parentHasPin(savedParentId)
            : await parentPinDb.familyAnyParentHasPin(decoded.familyId);

          if (needsPin) {
            return res.json({ message: 'Utloggad', needsParentPin: true });
          }
        } catch (err) {
          console.error('[AUTH] Logout: parent-pin check failed:', err.message);
          // On error, fall through to auto-restore (favor usability)
        }

        // No parent PIN → auto-restore parent session
        res.cookie('access_token', session.access_token, {
          httpOnly: true,
          secure: config.cookieSecure,
          sameSite: 'lax',
          maxAge: 15 * 60 * 1000,
          path: '/',
        });
        res.cookie('refresh_token', session.refresh_token, {
          httpOnly: true,
          secure: config.cookieSecure,
          sameSite: 'lax',
          maxAge: 7 * 24 * 60 * 60 * 1000,
          path: '/api/auth',
        });
        res.clearCookie('stjarndag_parent_session', { path: '/' });
        return res.json({ message: 'Utloggad', sessionRestored: true });
      }
    }

    res.clearCookie('stjarndag_parent_session', { path: '/' });
    res.json({ message: 'Utloggad' });
  } catch (err) {
    console.error('[AUTH] Logout error:', err);
    clearAllSessionCookies(res);
    res.clearCookie('stjarndag_parent_session', { path: '/' });
    res.json({ message: 'Utloggad' });
  }
});

// ─── CSRF + refresh token routes ──────────────────────────────────────────────
router.use('/', require('./refresh'));

// ─── Child login route ────────────────────────────────────────────────────────
router.use('/', require('./child-login'));

// ─── Email-flow routes (verify / resend / forgot / reset) ─────────────────────
router.use('/', require('./email'));

// ─── OAuth Sign In routes (Apple + Google) ────────────────────────────────────
router.use('/', require('./oauth-apple'));
router.use('/', require('./oauth-google'));

module.exports = router;
