'use strict';

/**
 * Registration route (E2). POST /api/auth/register.
 * Creates family + parent, seeds default activities, sends verification email.
 * Mounted at /api/auth in index.js.
 */

const express = require('express');
const { v4: uuidv4 } = require('uuid');
const { hashPassword } = require('../../lib/hash');
const db = require('../../lib/db');
const config = require('../../lib/config');
const { registrationLimiter } = require('../../middleware/rateLimiter');
const { sendVerificationEmail, registerContact } = require('../../lib/email');
const { sendWelcomeEmail } = require('../../lib/welcome-mailer');
const { createNewsletterSubscription } = require('../../lib/newsletter-subscribe');
const { validate } = require('../../middleware/validate');
const { RegisterSchema } = require('../../lib/schemas');
const { resolvePreAuthLocale } = require('../../lib/locale');
const { resolveAuthApiLocale, authApiMessage } = require('../../lib/auth-api-messages');
const { loadDefaultContent } = require('../../lib/default-content');
const { seedFamilyStarterActivitiesFromCanonicalDb } = require('../../lib/standard-library-family-seed');
const { lookupDefaultRewardIdForSeed } = require('../../lib/reward-provenance');
const { t } = require('../../lib/i18n');
const { SELECTION_SOURCES, OFFER_STATES } = require('../../lib/locale-selection');
const { enableEnglishAppForFamily } = require('../../lib/i18n-enable-english');
const {
  resolveRegistrationCountry,
  isKnownRegistrationCountryCode,
  normalizeCountryCode,
} = require('../../lib/market-region');
const { getMarketConfig } = require('../../lib/market-config');
const { assertRegistrationMarketOpen } = require('../../lib/registration-market-context');

const router = express.Router();

// ─── POST /api/auth/register ──────────────────────────────
router.post('/register', registrationLimiter, validate(RegisterSchema), async (req, res) => {
  const preAuthLang = resolveAuthApiLocale(req);
  try {
    // Registration is always open. Only maintenance mode blocks new signups.
    try {
      const result = await db.query("SELECT enabled FROM feature_flag WHERE key = 'maintenance_mode' LIMIT 1");
      if (result.rows.length > 0 && result.rows[0].enabled) {
        return res.status(403).json({ error: authApiMessage(preAuthLang, 'errors.registrationClosed') });
      }
    } catch (flagErr) {
      console.error('[AUTH] Feature flag check error:', flagErr);
    }

    const {
      email,
      password,
      name,
      family_name,
      referral_code: referralCodeRaw,
      utm_source: utmSource,
      utm_medium: utmMedium,
      utm_campaign: utmCampaign,
      utm_content: utmContent,
      utm_term: utmTerm,
      fbclid,
      preferred_locale: preferredLocaleRaw,
      language,
      country_code: countryCodeRaw,
    } = req.body;

    const localeExplicitlyChosen = Boolean(preferredLocaleRaw || language);
    const familyLocale = localeExplicitlyChosen
      ? resolvePreAuthLocale({
          explicit: preferredLocaleRaw || language,
          acceptLanguage: req.headers['accept-language'],
        })
      : resolvePreAuthLocale({ explicit: 'sv-SE' });
    const localeSelectionSource = localeExplicitlyChosen
      ? SELECTION_SOURCES.REGISTRATION
      : SELECTION_SOURCES.LEGACY_DEFAULT;
    const englishBetaOfferState = localeExplicitlyChosen
      ? OFFER_STATES.REGISTRATION_DECIDED
      : OFFER_STATES.NOT_SHOWN;

    const countryResolved = resolveRegistrationCountry({
      countryCodeRaw,
      localeExplicitlyChosen: localeExplicitlyChosen || Boolean(countryCodeRaw),
    });

    if (countryCodeRaw && !isKnownRegistrationCountryCode(normalizeCountryCode(countryCodeRaw))) {
      return res.status(400).json({ error: authApiMessage(familyLocale, 'errors.invalidCountry') });
    }

    const marketGate = await assertRegistrationMarketOpen(
      countryResolved.country_code,
      familyLocale
    );
    if (!marketGate.ok) {
      return res.status(marketGate.status).json({
        ...marketGate.body,
        market_region: countryResolved.market_region,
      });
    }

    if (!email || !password) {
      return res.status(400).json({ error: authApiMessage(familyLocale, 'errors.emailAndPasswordRequired') });
    }
    if (typeof email !== 'string' || !email.includes('@')) {
      return res.status(400).json({ error: authApiMessage(familyLocale, 'errors.emailInvalid') });
    }
    if (password.length < 8) {
      return res.status(400).json({ error: authApiMessage(familyLocale, 'errors.passwordTooShort') });
    }

    // Validate name — required for auto-generating family name
    if (!name || typeof name !== 'string' || name.trim().length < 1) {
      return res.status(400).json({ error: authApiMessage(familyLocale, 'errors.familyNameRequired') });
    }
    const trimmedName = name.trim();
    const isFamilyNameAutoGenerated = !family_name || family_name.trim() === '';
    const finalFamilyName = isFamilyNameAutoGenerated
      ? t(familyLocale, 'auth.register.familyNameSuffix', { name: trimmedName })
      : family_name.trim();

    const normalizedEmail = email.toLowerCase().trim();

    // Check if email exists
    const existing = await db.query(
      'SELECT id FROM parent WHERE LOWER(email) = $1',
      [normalizedEmail]
    );
    if (existing.rows.length > 0) {
      return res.status(409).json({ error: authApiMessage(familyLocale, 'errors.emailExists') });
    }

    const passwordHash = await hashPassword(password);
    const client = await db.getClient();

    try {
      await client.query('BEGIN');

      // PAYMENTS V1 — grandfather by payment_start_at cutoff (not founder count).
      const { grantGrandfatheredOnCreate, syncAllLegacyMirrors, emptyPremium } = require('../../lib/family-entitlements');
      const { getPaymentStartAt, isFamilyEligibleForGrandfathering } = require('../../lib/payment-settings');
      const paymentStartAt = await getPaymentStartAt();

      // Create family — no DB trial for post-cutoff cohort (store trial via RevenueCat only).
      const marketConfig = getMarketConfig({
        countryCode: countryResolved.country_code,
        marketRegion: countryResolved.market_region,
        locale: familyLocale,
      });

      const familyResult = await client.query(
        `INSERT INTO family (
           name, timezone, subscription_status, trial_ends_at, is_lifetime_free, preferred_locale,
           locale_selected_at, locale_selection_source, english_beta_offer_state,
           country_code, market_region, country_selected_at, country_selection_source
         )
         VALUES ($1, $2, 'none', NULL, false, $3, NOW(), $4, $5, $6, $7, NOW(), $8)
         RETURNING id, created_at`,
        [
          finalFamilyName,
          marketConfig.timezone,
          familyLocale,
          localeSelectionSource,
          englishBetaOfferState,
          countryResolved.country_code,
          countryResolved.market_region,
          countryResolved.country_selection_source,
        ]
      );
      const familyId = familyResult.rows[0].id;
      const familyCreatedAt = familyResult.rows[0].created_at;
      const isPreCutoff = isFamilyEligibleForGrandfathering({
        countryCode: countryResolved.country_code,
        createdAt: familyCreatedAt,
        paymentStartAt,
      });

      if (familyLocale === 'en-GB') {
        await enableEnglishAppForFamily(familyId, { client });
      }

      console.log(`[AUTH] Family created — payment_start cutoff: ${isPreCutoff ? 'grandfathered' : 'paywall cohort'}`);

      // New parents always start unverified. They get a 24h grace period to log in
      // while they verify their email. After 24h, login is blocked until verified.
      // Newsletter subscription is auto-opt-in (newsletter_subscribed = true).
      const parentResult = await client.query(
        `INSERT INTO parent (family_id, email, password_hash, name, verified, newsletter_subscribed, family_role, onboarding_completed)
         VALUES ($1, $2, $3, $4, false, true, $5, false) RETURNING id`,
        [familyId, normalizedEmail, passwordHash, trimmedName, null]
      );
      const parentId = parentResult.rows[0].id;

      const defaultContent = loadDefaultContent(familyLocale);
      const {
        activities: defaultActivities,
        templateCategories: TEMPLATE_CATEGORIES,
        rewards: defaultRewardsList,
      } = defaultContent;
      const { resolveTimeGroup, resolveTimeOffset } = require('../../lib/default-content');

      // sv-SE: prefer admin global library when present (unchanged behaviour).
      let groupedActivities = null;
      if (familyLocale === 'sv-SE') {
        try {
          const grpResult = await client.query(
            `SELECT name, icon, category_name, star_value, sort_order, sub_steps,
                    COALESCE(template_group, schema_type) AS grp
             FROM default_activity_template
             WHERE COALESCE(template_group, schema_type) IS NOT NULL
             ORDER BY grp, category_name, sort_order ASC`
          );
          groupedActivities = grpResult.rows.length > 0 ? grpResult.rows : null;
        } catch {
          groupedActivities = null;
        }
      }

      // Create all 6 categories
      const categoryMap = {};
      for (const cat of TEMPLATE_CATEGORIES) {
        const catResult = await client.query(
          'INSERT INTO category (family_id, name, sort_order, is_default) VALUES ($1, $2, $3, true) RETURNING id',
          [familyId, cat.name, cat.sort_order]
        );
        categoryMap[cat.key] = catResult.rows[0].id;
      }

      // Seed activities: canonical DB snapshots (sv-SE) or locale default content fallback.
      // When canonical rows exist, they are the sole Standard Library authority for sv-SE.
      // en-GB / empty-DB paths use config/default-content/* — explicit LEGACY_BOOTSTRAP only.
      let activitiesSeededFromCanonical = false;
      if (familyLocale === 'sv-SE') {
        const canonicalCount = await client.query(
          `SELECT COUNT(*)::int AS count FROM default_activity_template WHERE canonical_id IS NOT NULL`
        );
        if (canonicalCount.rows[0].count > 0) {
          await seedFamilyStarterActivitiesFromCanonicalDb(client, familyId, categoryMap, familyLocale);
          activitiesSeededFromCanonical = true;
        }
      }

      if (!activitiesSeededFromCanonical) {
        if (groupedActivities) {
          for (const act of groupedActivities) {
            const catId = categoryMap[act.grp];
            if (!catId) continue;
            const timeGroup = resolveTimeGroup(act.category_name);
            const combinedSort = resolveTimeOffset(act.category_name) + (act.sort_order ?? 0);
            const tplResult = await client.query(
              'INSERT INTO activity_template (family_id, name, icon, category_id, star_value, is_favorite, time_group, schema_type, sort_order, source) VALUES ($1, $2, $3, $4, $5, false, $6, $7, $8, \'admin\') RETURNING id',
              [familyId, act.name, act.icon, catId, act.star_value, timeGroup, act.grp, combinedSort]
            );

            // Create sub-steps from default_activity_template.sub_steps JSONB
            const subSteps = act.sub_steps || [];
            if (Array.isArray(subSteps) && subSteps.length > 0) {
              for (let si = 0; si < subSteps.length; si++) {
                await client.query(
                  `INSERT INTO activity_sub_step (activity_template_id, name, icon, sort_order)
                   VALUES ($1, $2, $3, $4)`,
                  [tplResult.rows[0].id, subSteps[si].name, subSteps[si].icon || null, si]
                );
              }
            }
          }
        } else {
          for (const act of defaultActivities) {
            const catId = categoryMap[act.schema_type];
            if (!catId) continue;
            const timeGroup = resolveTimeGroup(act.category);
            const combinedSort = resolveTimeOffset(act.category) + (act.sort_order ?? 0);
            await client.query(
              'INSERT INTO activity_template (family_id, name, icon, category_id, star_value, is_favorite, time_group, schema_type, sort_order, source) VALUES ($1, $2, $3, $4, $5, false, $6, $7, $8, \'admin\')',
              [familyId, act.name, act.icon, catId, act.star_value, timeGroup, act.schema_type, combinedSort]
            );
          }
        }
      }

      // Seed default rewards: admin library for sv-SE, locale file fallback for en-GB.
      let rewardsSeeded = false;
      if (familyLocale === 'sv-SE') {
        try {
          const defaultRewards = await client.query(
            'SELECT id, name, icon, star_cost FROM default_reward ORDER BY sort_order ASC, star_cost ASC'
          );
          for (const r of defaultRewards.rows) {
            await client.query(
              `INSERT INTO reward (family_id, name, icon, star_cost, requires_approval, is_active, source_default_id, modified_by_family)
               VALUES ($1, $2, $3, $4, false, true, $5, false)`,
              [familyId, r.name, r.icon, r.star_cost, r.id]
            );
          }
          rewardsSeeded = defaultRewards.rows.length > 0;
        } catch {
          /* table missing */
        }
      }
      if (!rewardsSeeded && defaultRewardsList?.length) {
        for (const r of defaultRewardsList) {
          let sourceDefaultId = null;
          try {
            sourceDefaultId = await lookupDefaultRewardIdForSeed(client, r);
          } catch {
            /* default_reward table missing */
          }
          await client.query(
            `INSERT INTO reward (family_id, name, icon, star_cost, requires_approval, is_active, source_default_id, modified_by_family)
             VALUES ($1, $2, $3, $4, false, true, $5, false)`,
            [familyId, r.name, r.icon, r.star_cost, sourceDefaultId]
          );
        }
      }

      // Standard schedules are NOT seeded as family templates.
      // Parents browse the standard library (live admin data) and explicitly copy to children.
      // "Mina scheman" stays empty until the parent creates their own templates.

      // Create notification preferences
      await client.query(
        'INSERT INTO notification_preference (parent_id) VALUES ($1)',
        [parentId]
      );

      // Create verification token inside the transaction so it's atomic with user creation.
      // WHY: if this fails after COMMIT, the user exists but has no token — unrecoverable
      // without the resend endpoint.
      const verifyToken = uuidv4();
      await client.query(
        'INSERT INTO email_verification (parent_id, token, expires_at) VALUES ($1, $2, $3)',
        [parentId, verifyToken, new Date(Date.now() + config.verification.tokenExpiryHours * 3600_000)]
      );

      await createNewsletterSubscription(client, parentId, normalizedEmail);

      const grandfatherRow = await grantGrandfatheredOnCreate(familyId, familyCreatedAt, {
        client,
        countryCode: countryResolved.country_code,
      });
      if (!grandfatherRow) {
        await syncAllLegacyMirrors(familyId, emptyPremium(), { client });
      }

      await client.query('COMMIT');

      // Analytics: funnel step — signup_started (family just created)
      const tracker = require('../../lib/analytics-tracker');
      tracker.trackSignupStarted(familyId);
      // Durable first-touch attribution (normalized) — never blocks registration
      try {
        const {
          normalizeAttributionInput,
          recordFamilyAttribution,
          toAnalyticsMetadata,
        } = require('../../lib/acquisition-attribution');
        const rawAttr = {
          utm_source: utmSource,
          utm_medium: utmMedium,
          utm_campaign: utmCampaign,
          utm_content: utmContent,
          utm_term: utmTerm,
          referral_code: referralCodeRaw,
          landing_locale: familyLocale,
          platform: req.body.platform,
          first_touch_at: req.body.first_touch_at,
        };
        const normalized = normalizeAttributionInput(rawAttr);
        if (normalized) {
          await recordFamilyAttribution(familyId, rawAttr, { registeredAt: new Date() });
          tracker.trackSignupAttribution(familyId, toAnalyticsMetadata(normalized));
        } else if (utmSource || utmMedium || utmCampaign || utmContent || utmTerm) {
          // Fallback analytics-only (legacy) if normalize dropped everything
          const attribution = {};
          if (utmSource) attribution.utm_source = String(utmSource).slice(0, 64);
          if (utmMedium) attribution.utm_medium = String(utmMedium).slice(0, 64);
          if (utmCampaign) attribution.utm_campaign = String(utmCampaign).slice(0, 128);
          if (utmContent) attribution.utm_content = String(utmContent).slice(0, 128);
          if (utmTerm) attribution.utm_term = String(utmTerm).slice(0, 128);
          tracker.trackSignupAttribution(familyId, attribution);
        }
        // Link English waitlist → family when email matches (funnel, no auto-invite)
        try {
          const waitlistDb = require('../../../db/waitlist');
          if (typeof waitlistDb.linkWaitlistConversion === 'function') {
            const linked = await waitlistDb.linkWaitlistConversion(normalizedEmail, familyId);
            if (linked) {
              require('../../../db/analytics').track(familyId, 'waitlist_account_signup', {
                locale: familyLocale,
              }).catch(() => {});
            }
          }
        } catch (wlErr) {
          console.error('[AUTH] waitlist conversion link failed:', wlErr.message);
        }
      } catch (attrErr) {
        console.error('[AUTH] attribution persist failed:', attrErr.message);
      }
      const activationP0 = require('../../lib/activation-p0');
      activationP0.resolveDefaultActivationVariant(familyId)
        .then((variant) => activationP0.ensureActivationState(familyId, new Date(), variant))
        .catch((err) => {
          console.error('[AUTH] ensureActivationState failed for', familyId, ':', err.message);
        });
      require('../../lib/journey/ingest').ingestMilestoneAsync({
        familyId,
        milestone: 'account_created',
        source: 'system',
      });

      // Referral v0 — capture ?ref= at signup (no reward in v0)
      if (referralCodeRaw) {
        (async () => {
          try {
            const { isActivationFlagEnabled, FLAG_KEYS } = require('../../lib/activation-flags');
            const enabled = await isActivationFlagEnabled(FLAG_KEYS.referral, familyId);
            if (!enabled) return;
            const referralDb = require('../../../db/referral');
            const referrer = await referralDb.findReferrerByCode(referralCodeRaw);
            if (!referrer || referrer.family_id === familyId) return;
            await referralDb.createPendingReferral({
              referrerParentId: referrer.parent_id,
              referredFamilyId: familyId,
              code: referralCodeRaw.trim().toUpperCase(),
            });
            require('../../../db/analytics').track(familyId, 'referral_signup', {
              code: referralCodeRaw.trim().toUpperCase(),
            });
          } catch (refErr) {
            console.error('[AUTH] referral capture failed:', refErr.message);
          }
        })();
      }

      // Register contact (no-op with Resend — kept for compatibility)
      try {
        await registerContact(normalizedEmail, trimmedName, 'signup');
      } catch (err) {
        console.error('[AUTH] registerContact failed for', normalizedEmail, ':', err.message);
      }

      // Send verification email (blocking so errors are surfaced immediately)
      try {
        await sendVerificationEmail(normalizedEmail, verifyToken, familyLocale);
      } catch (err) {
        console.error('[AUTH] sendVerificationEmail FAILED for', normalizedEmail, ':', err.message);
        // Don't block HTTP response — user can still log in and request resend
      }

      // Send welcome email (fire-and-forget — don't block registration response)
      // Gate 2J: valkomstmail — only send if feature is live/dev for this family
      const { hasAccess } = require('../../../db/features');
      const welcomeEmailAllowed = await hasAccess(familyId, 'valkomstmail');
      if (welcomeEmailAllowed) {
        sendWelcomeEmail(normalizedEmail, parentId, {
          foralderns_namn: trimmedName,
          barnets_namn: '',
          locale: familyLocale,
        }).catch(err => {
          console.error('[AUTH] Welcome email send failed:', err.message);
        });
      }

      res.status(201).json({
        message: t(familyLocale, 'auth.register.success'),
        parentId,
        family_name: finalFamilyName,
        is_family_name_auto_generated: isFamilyNameAutoGenerated,
        parent_name: trimmedName,
        preferred_locale: familyLocale,
        ...(process.env.NODE_ENV !== 'production' && { verifyToken }),
      });
    } catch (err) {
      await client.query('ROLLBACK');
      throw err;
    } finally {
      client.release();
    }
  } catch (err) {
    console.error('[AUTH] Register error:', err);
    if (err.code === '23505' && require('../../lib/activation-first-completion').isParentEmailUniqueViolation(err)) {
      return res.status(409).json({ error: authApiMessage(preAuthLang, 'errors.emailExists') });
    }
    res.status(500).json({ error: authApiMessage(preAuthLang, 'errors.serverError') });
  }
});
module.exports = router;
