'use strict';

/**
 * Registration route (E2). POST /api/auth/register.
 * Creates family + parent, seeds default activities, sends verification email.
 * Mounted at /api/auth in index.js.
 */

const express = require('express');
const { v4: uuidv4 } = require('uuid');
const { hashPassword } = require('../../lib/hash');
const db = require('../../lib/db');
const config = require('../../lib/config');
const { registrationLimiter } = require('../../middleware/rateLimiter');
const { sendVerificationEmail, registerContact } = require('../../lib/email');
const { sendWelcomeEmail } = require('../../lib/welcome-mailer');
const { createNewsletterSubscription } = require('../../lib/newsletter-subscribe');
const { validate } = require('../../middleware/validate');
const { RegisterSchema } = require('../../lib/schemas');

const router = express.Router();

// ─── POST /api/auth/register ──────────────────────────────
router.post('/register', registrationLimiter, validate(RegisterSchema), async (req, res) => {
  try {
    // Registration is always open. Only maintenance mode blocks new signups.
    try {
      const result = await db.query("SELECT enabled FROM feature_flag WHERE key = 'maintenance_mode' LIMIT 1");
      if (result.rows.length > 0 && result.rows[0].enabled) {
        return res.status(403).json({ error: 'Registrering är för närvarande stängd' });
      }
    } catch (flagErr) {
      console.error('[AUTH] Feature flag check error:', flagErr);
    }

    const {
      email,
      password,
      name,
      family_name,
      referral_code: referralCodeRaw,
      utm_source: utmSource,
      utm_medium: utmMedium,
      utm_campaign: utmCampaign,
      utm_content: utmContent,
      utm_term: utmTerm,
      fbclid,
    } = req.body;

    if (!email || !password) {
      return res.status(400).json({ error: 'E-post och lösenord krävs' });
    }
    if (typeof email !== 'string' || !email.includes('@')) {
      return res.status(400).json({ error: 'Ogiltig e-postadress' });
    }
    if (password.length < 8) {
      return res.status(400).json({ error: 'Lösenordet måste vara minst 8 tecken' });
    }

    // Validate name — required for auto-generating family name
    if (!name || typeof name !== 'string' || name.trim().length < 1) {
      return res.status(400).json({ error: 'Namn krävs för att skapa ett familjkonto' });
    }
    const trimmedName = name.trim();
    const isFamilyNameAutoGenerated = !family_name || family_name.trim() === '';
    const finalFamilyName = isFamilyNameAutoGenerated
      ? `${trimmedName}s familj`
      : family_name.trim();

    const normalizedEmail = email.toLowerCase().trim();

    // Check if email exists
    const existing = await db.query(
      'SELECT id FROM parent WHERE LOWER(email) = $1',
      [normalizedEmail]
    );
    if (existing.rows.length > 0) {
      return res.status(409).json({ error: 'Det finns redan ett konto med den e-postadressen' });
    }

    const passwordHash = await hashPassword(password);
    const client = await db.getClient();

    try {
      await client.query('BEGIN');

      // Determine is_lifetime_free: first N families (admin founder limit) get it automatically.
      // Count + insert in same transaction to prevent race condition.
      // Families beyond #200 require a paid subscription.
      const countResult = await client.query('SELECT COUNT(*)::int AS count FROM family');
      const familyCount = countResult.rows[0].count;
      const { getFounderFamilyLimitWithClient, qualifiesForLifetimeFree } = require('../../lib/payment-policy');
      const founderLimit = await getFounderFamilyLimitWithClient(client);
      const isLifetimeFree = qualifiesForLifetimeFree(familyCount, founderLimit);

      // Create family — subscription_status defaults to 'none' (CHECK constraint).
      // Trial access is tracked via trial_ends_at + family_subscriptions table.
      const familyResult = await client.query(
        `INSERT INTO family (name, subscription_status, trial_ends_at, is_lifetime_free)
         VALUES ($1, 'none', NOW() + INTERVAL '14 days', $2)
         RETURNING id`,
        [finalFamilyName, isLifetimeFree]
      );
      const familyId = familyResult.rows[0].id;

      console.log(`[AUTH] Family #${familyCount + 1} created — lifetime_free: ${isLifetimeFree} (limit ${founderLimit})`);

      // New parents always start unverified. They get a 24h grace period to log in
      // while they verify their email. After 24h, login is blocked until verified.
      // Newsletter subscription is auto-opt-in (newsletter_subscribed = true).
      const parentResult = await client.query(
        `INSERT INTO parent (family_id, email, password_hash, name, verified, newsletter_subscribed, family_role, onboarding_completed)
         VALUES ($1, $2, $3, $4, false, true, $5, false) RETURNING id`,
        [familyId, normalizedEmail, passwordHash, trimmedName, 'förälder']
      );
      const parentId = parentResult.rows[0].id;

      // Load admin-defined default templates (falls back to hardcoded if table doesn't exist yet).
      // Include schema_type so each template is tagged for age-based filtering during child creation.
      let defaultActivities;
      try {
        const tplResult = await client.query(
          `SELECT name, icon, category_name, star_value, sort_order, schema_type
           FROM default_activity_template ORDER BY schema_type ASC, category_name ASC, sort_order ASC`
        );
        defaultActivities = tplResult.rows.length > 0
          ? tplResult.rows.map(r => ({ name: r.name, icon: r.icon, category: r.category_name, star_value: r.star_value, sort_order: r.sort_order, schema_type: r.schema_type || 'forskola' }))
          : null;
      } catch {
        defaultActivities = null; // table doesn't exist yet
      }

      if (!defaultActivities) {
        defaultActivities = [
          // Förskola defaults (ages 2-5)
          { name: 'Vakna',                   icon: '🛏️', category: 'Morgon',      star_value: 1, sort_order: 0, schema_type: 'forskola' },
          { name: 'Klä på sig',              icon: '🌟', category: 'Morgon',      star_value: 1, sort_order: 1, schema_type: 'forskola' },
          { name: 'Borsta tänderna',          icon: '🪥', category: 'Morgon',      star_value: 1, sort_order: 2, schema_type: 'forskola' },
          { name: 'Äta frukost',             icon: '🍳', category: 'Morgon',      star_value: 1, sort_order: 3, schema_type: 'forskola' },
          { name: 'Förskola/Skola',          icon: '🏫', category: 'Förmiddag',   star_value: 1, sort_order: 0, schema_type: 'forskola' },
          { name: 'Leka ute',                icon: '🛝', category: 'Förmiddag',   star_value: 1, sort_order: 1, schema_type: 'forskola' },
          { name: 'Pyssel',                  icon: '🎨', category: 'Förmiddag',   star_value: 1, sort_order: 2, schema_type: 'forskola' },
          { name: 'Mellanmål',               icon: '🍎', category: 'Eftermiddag', star_value: 1, sort_order: 0, schema_type: 'forskola' },
          { name: 'Leka',                    icon: '🧩', category: 'Eftermiddag', star_value: 1, sort_order: 1, schema_type: 'forskola' },
          { name: 'Träning/Aktivitet',       icon: '🏃', category: 'Eftermiddag', star_value: 1, sort_order: 2, schema_type: 'forskola' },
          { name: 'Middag',                  icon: '🍽️', category: 'Kväll',       star_value: 1, sort_order: 0, schema_type: 'forskola' },
          { name: 'Borsta tänderna (kväll)',  icon: '🪥', category: 'Kväll',       star_value: 1, sort_order: 1, schema_type: 'forskola' },
          { name: 'Pyjamas',                 icon: '🧸', category: 'Kväll',       star_value: 1, sort_order: 2, schema_type: 'forskola' },
          { name: 'Godnattsaga',             icon: '📕', category: 'Kväll',       star_value: 1, sort_order: 3, schema_type: 'forskola' },
          { name: 'Sova',                    icon: '😴', category: 'Kväll',       star_value: 1, sort_order: 4, schema_type: 'forskola' },
          // Skola defaults (ages 6+)
          { name: 'Vakna & klä på sig',      icon: '🌅', category: 'Morgon',      star_value: 1, sort_order: 0, schema_type: 'skola' },
          { name: 'Frukost',                 icon: '🥣', category: 'Morgon',      star_value: 1, sort_order: 1, schema_type: 'skola' },
          { name: 'Borsta tänderna',          icon: '🪥', category: 'Morgon',      star_value: 1, sort_order: 2, schema_type: 'skola' },
          { name: 'Packa skolväska',          icon: '🎒', category: 'Morgon',      star_value: 1, sort_order: 3, schema_type: 'skola' },
          { name: 'Skola',                   icon: '🏫', category: 'Förmiddag',   star_value: 2, sort_order: 0, schema_type: 'skola' },
          { name: 'Rast & lek',              icon: '⚽', category: 'Förmiddag',   star_value: 1, sort_order: 1, schema_type: 'skola' },
          { name: 'Mellanmål',               icon: '🍎', category: 'Eftermiddag', star_value: 1, sort_order: 0, schema_type: 'skola' },
          { name: 'Läxor',                   icon: '📚', category: 'Eftermiddag', star_value: 2, sort_order: 1, schema_type: 'skola' },
          { name: 'Fritidsaktivitet',         icon: '🏃', category: 'Eftermiddag', star_value: 2, sort_order: 2, schema_type: 'skola' },
          { name: 'Middag',                  icon: '🍽️', category: 'Kväll',       star_value: 1, sort_order: 0, schema_type: 'skola' },
          { name: 'Borsta tänderna (kväll)',  icon: '🪥', category: 'Kväll',       star_value: 1, sort_order: 1, schema_type: 'skola' },
          { name: 'Läsa',                    icon: '📖', category: 'Kväll',       star_value: 1, sort_order: 2, schema_type: 'skola' },
          { name: 'Sova',                    icon: '😴', category: 'Kväll',       star_value: 1, sort_order: 3, schema_type: 'skola' },
        ];
      }

      // Create SIX template categories: Förskola, Skola, Morgon, Dag, Kväll, Helg
      // Each category corresponds to a standard template group that parents can customize.
      const TEMPLATE_CATEGORIES = [
        { key: 'forskola', name: 'Förskola', sort_order: 0 },
        { key: 'skola',    name: 'Skola',    sort_order: 1 },
        { key: 'morgon',   name: 'Morgon',   sort_order: 2 },
        { key: 'dag',      name: 'Dag',      sort_order: 3 },
        { key: 'kvall',    name: 'Kväll',    sort_order: 4 },
        { key: 'helg',     name: 'Helg',     sort_order: 5 },
      ];
      // Time-of-day sort multipliers to preserve ordering within each category:
      const TIME_CATEGORY_OFFSET = { 'Morgon': 0, 'Förmiddag': 100, 'Eftermiddag': 200, 'Kväll': 300 };
      // Map category_name to time_group
      const CATEGORY_TO_TIME_GROUP = {
        'Morgon': 'morgon', 'Förmiddag': 'formiddag',
        'Eftermiddag': 'eftermiddag', 'Kväll': 'kvall',
      };

      // Create all 6 categories
      const categoryMap = {};
      for (const cat of TEMPLATE_CATEGORIES) {
        const catResult = await client.query(
          'INSERT INTO category (family_id, name, sort_order, is_default) VALUES ($1, $2, $3, true) RETURNING id',
          [familyId, cat.name, cat.sort_order]
        );
        categoryMap[cat.key] = catResult.rows[0].id;
      }

      // Seed activities from default_activity_template using template_group.
      // Migration 050 cleared template_group/schema_type to NULL — filter those out
      // and fall back to hardcoded defaults if no grouped activities remain.
      let groupedActivities;
      try {
        const grpResult = await client.query(
          `SELECT name, icon, category_name, star_value, sort_order, sub_steps,
                  COALESCE(template_group, schema_type) AS grp
           FROM default_activity_template
           WHERE COALESCE(template_group, schema_type) IS NOT NULL
           ORDER BY grp, category_name, sort_order ASC`
        );
        groupedActivities = grpResult.rows.length > 0 ? grpResult.rows : null;
      } catch {
        groupedActivities = null;
      }

      if (groupedActivities) {
        for (const act of groupedActivities) {
          const catId = categoryMap[act.grp];
          if (!catId) continue; // skip unknown groups
          const timeGroup = CATEGORY_TO_TIME_GROUP[act.category_name] || 'morgon';
          const timeOffset = TIME_CATEGORY_OFFSET[act.category_name] ?? 400;
          const combinedSort = timeOffset + (act.sort_order ?? 0);
          const tplResult = await client.query(
            'INSERT INTO activity_template (family_id, name, icon, category_id, star_value, is_favorite, time_group, schema_type, sort_order) VALUES ($1, $2, $3, $4, $5, false, $6, $7, $8) RETURNING id',
            [familyId, act.name, act.icon, catId, act.star_value, timeGroup, act.grp, combinedSort]
          );

          // Create sub-steps from default_activity_template.sub_steps JSONB
          const subSteps = act.sub_steps || [];
          if (Array.isArray(subSteps) && subSteps.length > 0) {
            for (let si = 0; si < subSteps.length; si++) {
              await client.query(
                `INSERT INTO activity_sub_step (activity_template_id, name, icon, sort_order)
                 VALUES ($1, $2, $3, $4)`,
                [tplResult.rows[0].id, subSteps[si].name, subSteps[si].icon || null, si]
              );
            }
          }
        }
      } else {
        // Fallback: seed from hardcoded defaults into forskola/skola categories only
        for (const act of defaultActivities) {
          const catId = categoryMap[act.schema_type];
          if (!catId) continue;
          const timeGroup = CATEGORY_TO_TIME_GROUP[act.category] || 'morgon';
          const timeOffset = TIME_CATEGORY_OFFSET[act.category] ?? 400;
          const combinedSort = timeOffset + (act.sort_order ?? 0);
          await client.query(
            'INSERT INTO activity_template (family_id, name, icon, category_id, star_value, is_favorite, time_group, schema_type, sort_order) VALUES ($1, $2, $3, $4, $5, false, $6, $7, $8)',
            [familyId, act.name, act.icon, catId, act.star_value, timeGroup, act.schema_type, combinedSort]
          );
        }
      }

      // Seed default rewards from admin-defined library (fail-open: no default rewards if table missing)
      try {
        const defaultRewards = await client.query(
          'SELECT id, name, icon, star_cost FROM default_reward ORDER BY sort_order ASC, star_cost ASC'
        );
        for (const r of defaultRewards.rows) {
          await client.query(
            `INSERT INTO reward (family_id, name, icon, star_cost, requires_approval, is_active, source_default_id, modified_by_family)
             VALUES ($1, $2, $3, $4, false, true, $5, false)`,
            [familyId, r.name, r.icon, r.star_cost, r.id]
          );
        }
      } catch {
        // Table doesn't exist yet (pre-migration) — skip silently
      }

      // Standard schedules are NOT seeded as family templates.
      // Parents browse the standard library (live admin data) and explicitly copy to children.
      // "Mina scheman" stays empty until the parent creates their own templates.

      // Create notification preferences
      await client.query(
        'INSERT INTO notification_preference (parent_id) VALUES ($1)',
        [parentId]
      );

      // Create verification token inside the transaction so it's atomic with user creation.
      // WHY: if this fails after COMMIT, the user exists but has no token — unrecoverable
      // without the resend endpoint.
      const verifyToken = uuidv4();
      await client.query(
        'INSERT INTO email_verification (parent_id, token, expires_at) VALUES ($1, $2, $3)',
        [parentId, verifyToken, new Date(Date.now() + config.verification.tokenExpiryHours * 3600_000)]
      );

      await createNewsletterSubscription(client, parentId, normalizedEmail);

      // Create component-based subscription (14-day trial + basic_app)
      await client.query(
        `INSERT INTO family_subscriptions (family_id, tier, trial_expires_at, components)
         VALUES ($1, 'trial', NOW() + INTERVAL '14 days', $2)`,
        [
          familyId,
          JSON.stringify([{ component: 'basic_app', granted_at: new Date().toISOString(), expires_at: null }]),
        ]
      );

      await client.query('COMMIT');

      // Analytics: funnel step — signup_started (family just created)
      const tracker = require('../../lib/analytics-tracker');
      tracker.trackSignupStarted(familyId);
      const attribution = {};
      if (utmSource) attribution.utm_source = utmSource;
      if (utmMedium) attribution.utm_medium = utmMedium;
      if (utmCampaign) attribution.utm_campaign = utmCampaign;
      if (utmContent) attribution.utm_content = utmContent;
      if (utmTerm) attribution.utm_term = utmTerm;
      if (fbclid) attribution.fbclid = fbclid;
      if (Object.keys(attribution).length > 0) {
        tracker.trackSignupAttribution(familyId, attribution);
      }
      require('../../lib/activation-p0').ensureActivationState(familyId, new Date()).catch((err) => {
        console.error('[AUTH] ensureActivationState failed for', familyId, ':', err.message);
      });
      require('../../lib/journey/ingest').ingestMilestoneAsync({
        familyId,
        milestone: 'account_created',
        source: 'system',
      });

      // Referral v0 — capture ?ref= at signup (no reward in v0)
      if (referralCodeRaw) {
        (async () => {
          try {
            const { isActivationFlagEnabled, FLAG_KEYS } = require('../../lib/activation-flags');
            const enabled = await isActivationFlagEnabled(FLAG_KEYS.referral, familyId);
            if (!enabled) return;
            const referralDb = require('../../../db/referral');
            const referrer = await referralDb.findReferrerByCode(referralCodeRaw);
            if (!referrer || referrer.family_id === familyId) return;
            await referralDb.createPendingReferral({
              referrerParentId: referrer.parent_id,
              referredFamilyId: familyId,
              code: referralCodeRaw.trim().toUpperCase(),
            });
            require('../../../db/analytics').track(familyId, 'referral_signup', {
              code: referralCodeRaw.trim().toUpperCase(),
            });
          } catch (refErr) {
            console.error('[AUTH] referral capture failed:', refErr.message);
          }
        })();
      }

      // Register contact (no-op with Resend — kept for compatibility)
      try {
        await registerContact(normalizedEmail, trimmedName, 'signup');
      } catch (err) {
        console.error('[AUTH] registerContact failed for', normalizedEmail, ':', err.message);
      }

      // Send verification email (blocking so errors are surfaced immediately)
      try {
        await sendVerificationEmail(normalizedEmail, verifyToken);
      } catch (err) {
        console.error('[AUTH] sendVerificationEmail FAILED for', normalizedEmail, ':', err.message);
        // Don't block HTTP response — user can still log in and request resend
      }

      // Send welcome email (fire-and-forget — don't block registration response)
      // Gate 2J: valkomstmail — only send if feature is live/dev for this family
      const { hasAccess } = require('../../../db/features');
      const welcomeEmailAllowed = await hasAccess(familyId, 'valkomstmail');
      if (welcomeEmailAllowed) {
        sendWelcomeEmail(normalizedEmail, parentId, {
          foralderns_namn: trimmedName,
          barnets_namn: '',
        }).catch(err => {
          console.error('[AUTH] Welcome email send failed:', err.message);
        });
      }

      res.status(201).json({
        message: 'Konto skapat! Kontrollera din e-post för att verifiera ditt konto.',
        parentId,
        family_name: finalFamilyName,
        is_family_name_auto_generated: isFamilyNameAutoGenerated,
        parent_name: trimmedName,
        ...(process.env.NODE_ENV !== 'production' && { verifyToken }),
      });
    } catch (err) {
      await client.query('ROLLBACK');
      throw err;
    } finally {
      client.release();
    }
  } catch (err) {
    console.error('[AUTH] Register error:', err);
    res.status(500).json({ error: 'Något gick fel. Försök igen senare.' });
  }
});
module.exports = router;
