/**
 * Auth routes.
 * Owns: login, register, logout, token refresh, password reset, email verification.
 * Does NOT own: child schedule, family settings, push notifications.
 */
const express = require('express');
const jwt = require('jsonwebtoken');
const { v4: uuidv4 } = require('uuid');
const { hashPassword, comparePassword } = require('../lib/hash');
const db = require('../lib/db');
const config = require('../lib/config');
const crypto = require('crypto');
const { loginLimiter, childLoginLimiter, registrationLimiter, forgotPasswordLimiter, resendVerificationLimiter, appleLoginLimiter } = require('../middleware/rateLimiter');
const { getParentRoles, getChildrenForParent, syncAccountType } = require('../../db/parent-access');
const { requireAuth } = require('../middleware/auth');
const { generateCsrfToken } = require('../middleware/csrf');
const {
  createRefreshToken,
  verifyRefreshToken,
  revokeRefreshToken,
  revokeAllRefreshTokens,
  setRefreshCookie,
  clearRefreshCookie,
  setAccessCookie,
  clearAccessCookie,
} = require('../lib/refresh-tokens');
const {
  sendVerificationEmail,
  sendPasswordResetEmail,
  sendPinWarningEmail,
  registerContact,
} = require('../lib/email');
const { sendWelcomeEmail } = require('../lib/welcome-mailer');
const pinLockout = require('../../db/pin-lockout');
const { createSystemMessage } = require('../../db/system-messages');
const familySubscriptions = require('../../db/family-subscriptions');
const parentDb = require('../../db/parent');
const { broadcast } = require('../lib/sse-broadcast');
const { validate } = require('../middleware/validate');
const {
  RegisterSchema,
  LoginSchema,
  ChildLoginSchema,
  ForgotPasswordSchema,
  ResetPasswordSchema,
  VerifyEmailSchema,
  ResendVerificationSchema,
} = require('../lib/schemas');

const router = express.Router();

/**
 * Parse a jwt-style duration string ("15m", "8h") into seconds.
 * Falls back to the numeric value if already a number.
 */
function parseDuration(val) {
  if (typeof val === 'number') return val;
  const match = String(val).match(/^(\d+)([smhd])$/);
  if (!match) return 900; // default 15 minutes
  const num = parseInt(match[1], 10);
  const unit = match[2];
  if (unit === 's') return num;
  if (unit === 'm') return num * 60;
  if (unit === 'h') return num * 3600;
  if (unit === 'd') return num * 86400;
  return 900;
}

// ─── POST /api/auth/register ──────────────────────────────
router.post('/register', registrationLimiter, validate(RegisterSchema), async (req, res) => {
  try {
    // Registration is always open. Only maintenance mode blocks new signups.
    try {
      const result = await db.query("SELECT enabled FROM feature_flag WHERE key = 'maintenance_mode' LIMIT 1");
      if (result.rows.length > 0 && result.rows[0].enabled) {
        return res.status(403).json({ error: 'Registrering är för närvarande stängd' });
      }
    } catch (flagErr) {
      console.error('[AUTH] Feature flag check error:', flagErr);
    }

    const { email, password, name, family_name } = req.body;

    if (!email || !password) {
      return res.status(400).json({ error: 'E-post och lösenord krävs' });
    }
    if (typeof email !== 'string' || !email.includes('@')) {
      return res.status(400).json({ error: 'Ogiltig e-postadress' });
    }
    if (password.length < 8) {
      return res.status(400).json({ error: 'Lösenordet måste vara minst 8 tecken' });
    }

    // Validate name — required for auto-generating family name
    if (!name || typeof name !== 'string' || name.trim().length < 1) {
      return res.status(400).json({ error: 'Namn krävs för att skapa ett familjkonto' });
    }
    const trimmedName = name.trim();
    const isFamilyNameAutoGenerated = !family_name || family_name.trim() === '';
    const finalFamilyName = isFamilyNameAutoGenerated
      ? `${trimmedName}s familj`
      : family_name.trim();

    const normalizedEmail = email.toLowerCase().trim();

    // Check if email exists
    const existing = await db.query(
      'SELECT id FROM parent WHERE LOWER(email) = $1',
      [normalizedEmail]
    );
    if (existing.rows.length > 0) {
      return res.status(409).json({ error: 'Det finns redan ett konto med den e-postadressen' });
    }

    const passwordHash = await hashPassword(password);
    const client = await db.getClient();

    try {
      await client.query('BEGIN');

      // Determine is_lifetime_free: first 200 families get it automatically.
      // Count + insert in same transaction to prevent race condition.
      // Families beyond #200 require a paid subscription.
      const countResult = await client.query('SELECT COUNT(*)::int AS count FROM family');
      const familyCount = countResult.rows[0].count;
      const isLifetimeFree = familyCount < 200;

      // Create family — subscription_status defaults to 'none' (CHECK constraint).
      // Trial access is tracked via trial_ends_at + family_subscriptions table.
      const familyResult = await client.query(
        `INSERT INTO family (name, subscription_status, trial_ends_at, is_lifetime_free)
         VALUES ($1, 'none', NOW() + INTERVAL '14 days', $2)
         RETURNING id`,
        [finalFamilyName, isLifetimeFree]
      );
      const familyId = familyResult.rows[0].id;

      console.log(`[AUTH] Family #${familyCount + 1} created — lifetime_free: ${isLifetimeFree}`);

      // New parents always start unverified. They get a 24h grace period to log in
      // while they verify their email. After 24h, login is blocked until verified.
      // Newsletter subscription is auto-opt-in (newsletter_subscribed = true).
      const parentResult = await client.query(
        `INSERT INTO parent (family_id, email, password_hash, name, verified, newsletter_subscribed, family_role, onboarding_completed)
         VALUES ($1, $2, $3, $4, false, true, $5, false) RETURNING id`,
        [familyId, normalizedEmail, passwordHash, trimmedName, 'förälder']
      );
      const parentId = parentResult.rows[0].id;

      // Load admin-defined default templates (falls back to hardcoded if table doesn't exist yet).
      // Include schema_type so each template is tagged for age-based filtering during child creation.
      let defaultActivities;
      try {
        const tplResult = await client.query(
          `SELECT name, icon, category_name, star_value, sort_order, schema_type
           FROM default_activity_template ORDER BY schema_type ASC, category_name ASC, sort_order ASC`
        );
        defaultActivities = tplResult.rows.length > 0
          ? tplResult.rows.map(r => ({ name: r.name, icon: r.icon, category: r.category_name, star_value: r.star_value, sort_order: r.sort_order, schema_type: r.schema_type || 'forskola' }))
          : null;
      } catch {
        defaultActivities = null; // table doesn't exist yet
      }

      if (!defaultActivities) {
        defaultActivities = [
          // Förskola defaults (ages 2-5)
          { name: 'Vakna',                   icon: '🛏️', category: 'Morgon',      star_value: 1, sort_order: 0, schema_type: 'forskola' },
          { name: 'Klä på sig',              icon: '🌟', category: 'Morgon',      star_value: 1, sort_order: 1, schema_type: 'forskola' },
          { name: 'Borsta tänderna',          icon: '🪥', category: 'Morgon',      star_value: 1, sort_order: 2, schema_type: 'forskola' },
          { name: 'Äta frukost',             icon: '🍳', category: 'Morgon',      star_value: 1, sort_order: 3, schema_type: 'forskola' },
          { name: 'Förskola/Skola',          icon: '🏫', category: 'Förmiddag',   star_value: 1, sort_order: 0, schema_type: 'forskola' },
          { name: 'Leka ute',                icon: '🛝', category: 'Förmiddag',   star_value: 1, sort_order: 1, schema_type: 'forskola' },
          { name: 'Pyssel',                  icon: '🎨', category: 'Förmiddag',   star_value: 1, sort_order: 2, schema_type: 'forskola' },
          { name: 'Mellanmål',               icon: '🍎', category: 'Eftermiddag', star_value: 1, sort_order: 0, schema_type: 'forskola' },
          { name: 'Leka',                    icon: '🧩', category: 'Eftermiddag', star_value: 1, sort_order: 1, schema_type: 'forskola' },
          { name: 'Träning/Aktivitet',       icon: '🏃', category: 'Eftermiddag', star_value: 1, sort_order: 2, schema_type: 'forskola' },
          { name: 'Middag',                  icon: '🍽️', category: 'Kväll',       star_value: 1, sort_order: 0, schema_type: 'forskola' },
          { name: 'Borsta tänderna (kväll)',  icon: '🪥', category: 'Kväll',       star_value: 1, sort_order: 1, schema_type: 'forskola' },
          { name: 'Pyjamas',                 icon: '🧸', category: 'Kväll',       star_value: 1, sort_order: 2, schema_type: 'forskola' },
          { name: 'Godnattsaga',             icon: '📕', category: 'Kväll',       star_value: 1, sort_order: 3, schema_type: 'forskola' },
          { name: 'Sova',                    icon: '😴', category: 'Kväll',       star_value: 1, sort_order: 4, schema_type: 'forskola' },
          // Skola defaults (ages 6+)
          { name: 'Vakna & klä på sig',      icon: '🌅', category: 'Morgon',      star_value: 1, sort_order: 0, schema_type: 'skola' },
          { name: 'Frukost',                 icon: '🥣', category: 'Morgon',      star_value: 1, sort_order: 1, schema_type: 'skola' },
          { name: 'Borsta tänderna',          icon: '🪥', category: 'Morgon',      star_value: 1, sort_order: 2, schema_type: 'skola' },
          { name: 'Packa skolväska',          icon: '🎒', category: 'Morgon',      star_value: 1, sort_order: 3, schema_type: 'skola' },
          { name: 'Skola',                   icon: '🏫', category: 'Förmiddag',   star_value: 2, sort_order: 0, schema_type: 'skola' },
          { name: 'Rast & lek',              icon: '⚽', category: 'Förmiddag',   star_value: 1, sort_order: 1, schema_type: 'skola' },
          { name: 'Mellanmål',               icon: '🍎', category: 'Eftermiddag', star_value: 1, sort_order: 0, schema_type: 'skola' },
          { name: 'Läxor',                   icon: '📚', category: 'Eftermiddag', star_value: 2, sort_order: 1, schema_type: 'skola' },
          { name: 'Fritidsaktivitet',         icon: '🏃', category: 'Eftermiddag', star_value: 2, sort_order: 2, schema_type: 'skola' },
          { name: 'Middag',                  icon: '🍽️', category: 'Kväll',       star_value: 1, sort_order: 0, schema_type: 'skola' },
          { name: 'Borsta tänderna (kväll)',  icon: '🪥', category: 'Kväll',       star_value: 1, sort_order: 1, schema_type: 'skola' },
          { name: 'Läsa',                    icon: '📖', category: 'Kväll',       star_value: 1, sort_order: 2, schema_type: 'skola' },
          { name: 'Sova',                    icon: '😴', category: 'Kväll',       star_value: 1, sort_order: 3, schema_type: 'skola' },
        ];
      }

      // Create SIX template categories: Förskola, Skola, Morgon, Dag, Kväll, Helg
      // Each category corresponds to a standard template group that parents can customize.
      const TEMPLATE_CATEGORIES = [
        { key: 'forskola', name: 'Förskola', sort_order: 0 },
        { key: 'skola',    name: 'Skola',    sort_order: 1 },
        { key: 'morgon',   name: 'Morgon',   sort_order: 2 },
        { key: 'dag',      name: 'Dag',      sort_order: 3 },
        { key: 'kvall',    name: 'Kväll',    sort_order: 4 },
        { key: 'helg',     name: 'Helg',     sort_order: 5 },
      ];
      // Time-of-day sort multipliers to preserve ordering within each category:
      const TIME_CATEGORY_OFFSET = { 'Morgon': 0, 'Förmiddag': 100, 'Eftermiddag': 200, 'Kväll': 300 };
      // Map category_name to time_group
      const CATEGORY_TO_TIME_GROUP = {
        'Morgon': 'morgon', 'Förmiddag': 'formiddag',
        'Eftermiddag': 'eftermiddag', 'Kväll': 'kvall',
      };

      // Create all 6 categories
      const categoryMap = {};
      for (const cat of TEMPLATE_CATEGORIES) {
        const catResult = await client.query(
          'INSERT INTO category (family_id, name, sort_order, is_default) VALUES ($1, $2, $3, true) RETURNING id',
          [familyId, cat.name, cat.sort_order]
        );
        categoryMap[cat.key] = catResult.rows[0].id;
      }

      // Seed activities from default_activity_template using template_group.
      // Migration 050 cleared template_group/schema_type to NULL — filter those out
      // and fall back to hardcoded defaults if no grouped activities remain.
      let groupedActivities;
      try {
        const grpResult = await client.query(
          `SELECT name, icon, category_name, star_value, sort_order, sub_steps,
                  COALESCE(template_group, schema_type) AS grp
           FROM default_activity_template
           WHERE COALESCE(template_group, schema_type) IS NOT NULL
           ORDER BY grp, category_name, sort_order ASC`
        );
        groupedActivities = grpResult.rows.length > 0 ? grpResult.rows : null;
      } catch {
        groupedActivities = null;
      }

      if (groupedActivities) {
        for (const act of groupedActivities) {
          const catId = categoryMap[act.grp];
          if (!catId) continue; // skip unknown groups
          const timeGroup = CATEGORY_TO_TIME_GROUP[act.category_name] || 'morgon';
          const timeOffset = TIME_CATEGORY_OFFSET[act.category_name] ?? 400;
          const combinedSort = timeOffset + (act.sort_order ?? 0);
          const tplResult = await client.query(
            'INSERT INTO activity_template (family_id, name, icon, category_id, star_value, is_favorite, time_group, schema_type, sort_order) VALUES ($1, $2, $3, $4, $5, false, $6, $7, $8) RETURNING id',
            [familyId, act.name, act.icon, catId, act.star_value, timeGroup, act.grp, combinedSort]
          );

          // Create sub-steps from default_activity_template.sub_steps JSONB
          const subSteps = act.sub_steps || [];
          if (Array.isArray(subSteps) && subSteps.length > 0) {
            for (let si = 0; si < subSteps.length; si++) {
              await client.query(
                `INSERT INTO activity_sub_step (activity_template_id, name, icon, sort_order)
                 VALUES ($1, $2, $3, $4)`,
                [tplResult.rows[0].id, subSteps[si].name, subSteps[si].icon || null, si]
              );
            }
          }
        }
      } else {
        // Fallback: seed from hardcoded defaults into forskola/skola categories only
        for (const act of defaultActivities) {
          const catId = categoryMap[act.schema_type];
          if (!catId) continue;
          const timeGroup = CATEGORY_TO_TIME_GROUP[act.category] || 'morgon';
          const timeOffset = TIME_CATEGORY_OFFSET[act.category] ?? 400;
          const combinedSort = timeOffset + (act.sort_order ?? 0);
          await client.query(
            'INSERT INTO activity_template (family_id, name, icon, category_id, star_value, is_favorite, time_group, schema_type, sort_order) VALUES ($1, $2, $3, $4, $5, false, $6, $7, $8)',
            [familyId, act.name, act.icon, catId, act.star_value, timeGroup, act.schema_type, combinedSort]
          );
        }
      }

      // Seed default rewards from admin-defined library (fail-open: no default rewards if table missing)
      try {
        const defaultRewards = await client.query(
          'SELECT id, name, icon, star_cost FROM default_reward ORDER BY sort_order ASC, star_cost ASC'
        );
        for (const r of defaultRewards.rows) {
          await client.query(
            `INSERT INTO reward (family_id, name, icon, star_cost, requires_approval, is_active, source_default_id, modified_by_family)
             VALUES ($1, $2, $3, $4, false, true, $5, false)`,
            [familyId, r.name, r.icon, r.star_cost, r.id]
          );
        }
      } catch {
        // Table doesn't exist yet (pre-migration) — skip silently
      }

      // Standard schedules are NOT seeded as family templates.
      // Parents browse the standard library (live admin data) and explicitly copy to children.
      // "Mina scheman" stays empty until the parent creates their own templates.

      // Create notification preferences
      await client.query(
        'INSERT INTO notification_preference (parent_id) VALUES ($1)',
        [parentId]
      );

      // Create verification token inside the transaction so it's atomic with user creation.
      // WHY: if this fails after COMMIT, the user exists but has no token — unrecoverable
      // without the resend endpoint.
      const verifyToken = uuidv4();
      await client.query(
        'INSERT INTO email_verification (parent_id, token, expires_at) VALUES ($1, $2, $3)',
        [parentId, verifyToken, new Date(Date.now() + config.verification.tokenExpiryHours * 3600_000)]
      );

      // Auto-subscribe new parents to the newsletter (Del 1 of task #1562663).
      // newsletter_subscribed = true is set on the parent record; create the email_subscriptions
      // record so the parent appears in the admin subscriber list immediately.
      await client.query(
        `INSERT INTO email_subscriptions (parent_id, email, subscribed, subscribed_at, unsubscribe_token)
         VALUES ($1, $2, true, NOW(), gen_random_uuid())
         ON CONFLICT (parent_id) DO NOTHING`,
        [parentId, normalizedEmail]
      );

      // Create component-based subscription (14-day trial + basic_app)
      await client.query(
        `INSERT INTO family_subscriptions (family_id, tier, trial_expires_at, components)
         VALUES ($1, 'trial', NOW() + INTERVAL '14 days', $2)`,
        [
          familyId,
          JSON.stringify([{ component: 'basic_app', granted_at: new Date().toISOString(), expires_at: null }]),
        ]
      );

      await client.query('COMMIT');

      // Analytics: funnel step — signup_started (family just created)
      require('../lib/analytics-tracker').trackSignupStarted(familyId);

      // Register as contact FIRST so the email proxy accepts the verification mail
      // (proxy blocks cold outreach unless the recipient is a known contact).
      // This must complete before we call sendVerificationEmail — race = 429.
      try {
        await registerContact(normalizedEmail, trimmedName, 'signup');
      } catch (err) {
        console.error('[AUTH] registerContact FAILED for', normalizedEmail, ':', err.message);
        // Block — can't send verification email if proxy doesn't know this contact
        return res.status(503).json({ error: 'Kunde inte initiera e-postverifiering. Försök igen.' });
      }

      // Send verification email (blocking so errors are surfaced immediately)
      try {
        await sendVerificationEmail(normalizedEmail, verifyToken);
      } catch (err) {
        console.error('[AUTH] sendVerificationEmail FAILED for', normalizedEmail, ':', err.message);
        // Don't block HTTP response — user can still log in and request resend
      }

      // Send welcome email (fire-and-forget — don't block registration response)
      // Gate 2J: valkomstmail — only send if feature is live/dev for this family
      const { hasAccess } = require('../../db/features');
      const welcomeEmailAllowed = await hasAccess(familyId, 'valkomstmail');
      if (welcomeEmailAllowed) {
        sendWelcomeEmail(normalizedEmail, parentId, {
          foralderns_namn: trimmedName,
          barnets_namn: '',
        }).catch(err => {
          console.error('[AUTH] Welcome email send failed:', err.message);
        });
      }

      res.status(201).json({
        message: 'Konto skapat! Kontrollera din e-post för att verifiera ditt konto.',
        parentId,
        family_name: finalFamilyName,
        is_family_name_auto_generated: isFamilyNameAutoGenerated,
        parent_name: trimmedName,
        ...(process.env.NODE_ENV !== 'production' && { verifyToken }),
      });
    } catch (err) {
      await client.query('ROLLBACK');
      throw err;
    } finally {
      client.release();
    }
  } catch (err) {
    console.error('[AUTH] Register error:', err);
    res.status(500).json({ error: 'Något gick fel. Försök igen senare.' });
  }
});

// ─── POST /api/auth/login ─────────────────────────────────
router.post('/login', loginLimiter, validate(LoginSchema), async (req, res) => {
  try {
    const { email, password } = req.body;
    if (!email || !password) {
      return res.status(400).json({ error: 'E-post och lösenord krävs' });
    }

    const normalizedEmail = email.toLowerCase().trim();
    const result = await db.query(
      'SELECT id, family_id, email, password_hash, verified, is_admin, created_at, COALESCE(locked, false) as locked, COALESCE(onboarding_completed, true) as onboarding_completed FROM parent WHERE LOWER(email) = $1',
      [normalizedEmail]
    );

    // Log attempt
    await db.query(
      'INSERT INTO login_attempt (identifier, ip_address, success) VALUES ($1, $2, $3)',
      [normalizedEmail, req.ip || 'unknown', false]
    );

    const parent = result.rows[0];
    if (!parent || !(await comparePassword(password, parent.password_hash))) {
      return res.status(401).json({ error: 'Felaktig e-post eller lösenord' });
    }

    if (parent.locked) {
      return res.status(403).json({ error: 'Ditt konto har spärrats. Kontakta administratören.' });
    }

    // Email verification with 24h grace period.
    // New registrations can log in freely for 24h without verifying.
    // After that, verification is enforced.
    if (!parent.verified) {
      const createdAt = new Date(parent.created_at);
      const gracePeriodMs = 24 * 60 * 60 * 1000;
      const graceDeadline = new Date(createdAt.getTime() + gracePeriodMs);
      const now = new Date();

      if (now > graceDeadline) {
        return res.status(403).json({
          error: 'Du måste verifiera din e-postadress för att fortsätta',
          code: 'EMAIL_VERIFICATION_REQUIRED',
          email: normalizedEmail,
        });
      }
      // Within grace period — allow login but include verification status
    }

    // Mark attempt as success
    await db.query(
      `UPDATE login_attempt SET success = true
       WHERE identifier = $1 AND created_at >= NOW() - INTERVAL '1 second'`,
      [normalizedEmail]
    );

    // Record login event for analytics
    const loginRole = parent.is_admin ? 'admin' : 'parent';
    db.query(
      'INSERT INTO login_event (user_id, role, family_id) VALUES ($1, $2, $3)',
      [parent.id, loginRole, parent.family_id]
    ).catch(() => {}); // fire-and-forget, never block the response

    const accessToken = jwt.sign(
      {
        id: parent.id,
        type: 'parent',
        familyId: parent.family_id,
        email: parent.email,
        isAdmin: parent.is_admin,
      },
      config.jwt.secret,
      { expiresIn: config.jwt.expiresIn }
    );

    // Issue 7-day refresh token (stored hashed in DB, raw value in httpOnly cookie)
    const rawRefresh = await createRefreshToken({
      userId: parent.id,
      userType: 'parent',
      familyId: parent.family_id,
    });
    setRefreshCookie(res, rawRefresh);

    // Set access token as httpOnly cookie — XSS cannot read it.
    // Cookie maxAge matches JWT TTL so they expire together.
    const expiresInSecs = typeof config.jwt.expiresIn === 'string'
      ? parseDuration(config.jwt.expiresIn)
      : config.jwt.expiresIn;
    setAccessCookie(res, accessToken, expiresInSecs);

    // Issue fresh CSRF token for the new session
    const csrfToken = generateCsrfToken(res);

    const user = {
      id: parent.id,
      email: parent.email,
      familyId: parent.family_id,
      isAdmin: parent.is_admin,
      type: 'parent',
      onboarding_completed: parent.onboarding_completed,
    };

    // expiresAt lets the frontend schedule proactive silent refresh
    // (the access token itself is in an httpOnly cookie — JS can't decode it)
    const expiresAt = Date.now() + expiresInSecs * 1000;
    res.json({ csrfToken, user, expiresAt });
  } catch (err) {
    console.error('[AUTH] Login error:', err);
    res.status(500).json({ error: 'Något gick fel. Försök igen senare.' });
  }
});

// ─── POST /api/auth/verify-email ──────────────────────────
router.post('/verify-email', validate(VerifyEmailSchema), async (req, res) => {
  try {
    const { token } = req.body;
    if (!token) {
      return res.status(400).json({ error: 'Verifieringstoken krävs' });
    }

    const result = await db.query(
      'SELECT id, parent_id, expires_at FROM email_verification WHERE token = $1',
      [token]
    );

    const verification = result.rows[0];
    if (!verification || new Date(verification.expires_at) < new Date()) {
      return res.status(400).json({ error: 'Ogiltig eller utgången verifieringslänk' });
    }

    await db.query('UPDATE parent SET verified = true WHERE id = $1', [verification.parent_id]);
    await db.query('DELETE FROM email_verification WHERE id = $1', [verification.id]);

    // Analytics: funnel step — email_verified
    db.query('SELECT family_id FROM parent WHERE id = $1', [verification.parent_id])
      .then(r => {
        if (r.rows[0]) require('../lib/analytics-tracker').trackEmailVerified(r.rows[0].family_id);
      })
      .catch(() => {});

    res.json({ message: 'E-postadressen har verifierats! Du kan nu logga in.' });
  } catch (err) {
    console.error('[AUTH] Verify error:', err);
    res.status(500).json({ error: 'Något gick fel. Försök igen senare.' });
  }
});

// ─── POST /api/auth/resend-verification ───────────────────
// Rate limited: max 3 per hour per email. Generates a fresh token each time.
router.post('/resend-verification', resendVerificationLimiter, validate(ResendVerificationSchema), async (req, res) => {
  try {
    const { email } = req.body;
    if (!email) {
      return res.status(400).json({ error: 'E-postadress krävs' });
    }

    const normalizedEmail = email.toLowerCase().trim();

    // Always return success to avoid leaking account existence
    const successMessage = 'Om kontot finns skickas en ny verifieringslänk';

    const parentResult = await db.query(
      'SELECT id, name, verified FROM parent WHERE LOWER(email) = $1',
      [normalizedEmail]
    );

    if (parentResult.rows.length === 0) {
      return res.json({ message: successMessage });
    }

    const parent = parentResult.rows[0];

    // Already verified — no need to resend
    if (parent.verified) {
      return res.json({ message: successMessage });
    }

    // Rate limit: max 3 resend requests per hour per email (DB-based)
    const recentResult = await db.query(
      `SELECT resend_count, last_resent_at FROM email_verification
       WHERE parent_id = $1 ORDER BY created_at DESC LIMIT 1`,
      [parent.id]
    );

    if (recentResult.rows.length > 0) {
      const { resend_count, last_resent_at } = recentResult.rows[0];
      if (last_resent_at) {
        const hourAgo = new Date(Date.now() - 60 * 60 * 1000);
        if (new Date(last_resent_at) > hourAgo && resend_count >= 3) {
          return res.status(429).json({
            error: 'Du har redan begärt flera verifieringslänkar. Försök igen om en timme.',
          });
        }
      }
    }

    // Delete old tokens and create a fresh one
    await db.query('DELETE FROM email_verification WHERE parent_id = $1', [parent.id]);

    const verifyToken = uuidv4();
    await db.query(
      `INSERT INTO email_verification (parent_id, token, expires_at, resend_count, last_resent_at)
       VALUES ($1, $2, $3, $4, NOW())`,
      [
        parent.id,
        verifyToken,
        new Date(Date.now() + config.verification.tokenExpiryHours * 3600_000),
        (recentResult.rows[0]?.resend_count || 0) + 1,
      ]
    );

    await sendVerificationEmail(normalizedEmail, verifyToken);

    res.json({ message: successMessage });
  } catch (err) {
    console.error('[AUTH] Resend verification error:', err);
    res.status(500).json({ error: 'Något gick fel. Försök igen senare.' });
  }
});

// ─── POST /api/auth/forgot-password ───────────────────────
router.post('/forgot-password', forgotPasswordLimiter, validate(ForgotPasswordSchema), async (req, res) => {
  console.log('[AUTH] POST /forgot-password — request received');
  try {
    const { email } = req.body;
    if (!email) {
      console.log('[AUTH] forgot-password: missing email in body');
      return res.status(400).json({ error: 'E-postadress krävs' });
    }

    const normalizedEmail = email.toLowerCase().trim();
    console.log('[AUTH] forgot-password: looking up email', normalizedEmail);
    // Security: always return the same message regardless of whether email exists
    const successMessage = 'Om e-postadressen finns skickar vi en länk';

    const result = await db.query(
      'SELECT id, name FROM parent WHERE LOWER(email) = $1',
      [normalizedEmail]
    );

    if (result.rows.length === 0) {
      console.log('[AUTH] forgot-password: email not found in DB (returning generic success)');
      return res.json({ message: successMessage });
    }

    const parent = result.rows[0];
    console.log('[AUTH] forgot-password: found parent', parent.id);

    // Invalidate existing tokens
    await db.query(
      'UPDATE password_reset SET used = true WHERE parent_id = $1 AND used = false',
      [parent.id]
    );

    // Create new token — 64 hex chars (crypto.randomBytes(32))
    const resetToken = crypto.randomBytes(32).toString('hex');
    const expiresAt = new Date(Date.now() + config.verification.resetTokenExpiryHours * 3600_000);
    await db.query(
      'INSERT INTO password_reset (parent_id, token, expires_at) VALUES ($1, $2, $3)',
      [parent.id, resetToken, expiresAt]
    );
    console.log('[AUTH] forgot-password: token created, expires at', expiresAt.toISOString());

    const emailResult = await sendPasswordResetEmail(normalizedEmail, resetToken, parent.name);
    if (!emailResult || !emailResult.success) {
      console.error('[AUTH] Password reset email delivery FAILED:', JSON.stringify(emailResult));
    } else {
      console.log('[AUTH] Password reset email sent OK to:', normalizedEmail, 'via', emailResult.provider);
    }

    res.json({
      message: successMessage,
      ...(process.env.NODE_ENV !== 'production' && { resetToken }),
    });
  } catch (err) {
    console.error('[AUTH] Forgot password error:', err.message, err.stack);
    res.status(500).json({ error: 'Något gick fel. Försök igen senare.' });
  }
});

// ─── POST /api/auth/reset-password ────────────────────────
router.post('/reset-password', validate(ResetPasswordSchema), async (req, res) => {
  console.log('[AUTH] POST /reset-password — request received');
  try {
    const { token, password } = req.body;
    if (!token || !password) {
      return res.status(400).json({ error: 'Token och lösenord krävs' });
    }
    if (password.length < 8) {
      return res.status(400).json({ error: 'Lösenordet måste vara minst 8 tecken' });
    }

    const result = await db.query(
      'SELECT id, parent_id, expires_at, used FROM password_reset WHERE token = $1',
      [token]
    );

    const reset = result.rows[0];
    if (!reset || reset.used || new Date(reset.expires_at) < new Date()) {
      console.log('[AUTH] reset-password: invalid/expired/used token');
      return res.status(400).json({ error: 'Ogiltig eller utgången återställningslänk. Begär en ny återställningslänk.' });
    }

    const passwordHash = await hashPassword(password);
    const client = await db.getClient();

    try {
      await client.query('BEGIN');
      await client.query('UPDATE parent SET password_hash = $1 WHERE id = $2', [passwordHash, reset.parent_id]);
      await client.query('UPDATE password_reset SET used = true WHERE id = $1', [reset.id]);
      await client.query('COMMIT');
      console.log('[AUTH] reset-password: password updated for parent', reset.parent_id);
    } catch (err) {
      await client.query('ROLLBACK');
      throw err;
    } finally {
      client.release();
    }

    // Revoke ALL refresh tokens so stolen tokens can't outlive the password reset.
    // Without this, a compromised refresh token remains valid for up to 30 days.
    await revokeAllRefreshTokens({ userId: reset.parent_id, userType: 'parent' });

    res.json({ message: 'Lösenordet har ändrats! Du kan nu logga in.' });
  } catch (err) {
    console.error('[AUTH] Reset password error:', err.message, err.stack);
    res.status(500).json({ error: 'Något gick fel. Försök igen senare.' });
  }
});

// ─── POST /api/auth/child-login ───────────────────────────
// Requires BOTH name + PIN. Tracks attempts in pin_lockout table with
// exponential backoff (5 attempts → 1min, 8 → 5min, 11 → 15min).
// Notifies parent at 3rd failed attempt (in-app + email, with email cooldown).
router.post('/child-login', childLoginLimiter, validate(ChildLoginSchema), async (req, res) => {
  try {
    const { username, pin } = req.body;

    if (!username || !username.trim()) {
      return res.status(400).json({ error: 'Namn krävs' });
    }
    if (!pin) {
      return res.status(400).json({ error: 'PIN-kod krävs' });
    }
    if (!/^\d{4}$/.test(pin)) {
      return res.status(400).json({ error: 'PIN-koden måste vara 4 siffror' });
    }

    const normalizedInput = username.toLowerCase().trim();
    const clientIp = req.ip || 'unknown';

    // Find child — username match first, then display name
    let childResult = await db.query(
      'SELECT id, family_id, name, emoji, username, pin FROM child WHERE LOWER(username) = $1',
      [normalizedInput]
    );
    let child = childResult.rows[0];

    if (!child) {
      const nameResult = await db.query(
        'SELECT id, family_id, name, emoji, username, pin FROM child WHERE LOWER(name) = $1',
        [normalizedInput]
      );
      if (nameResult.rows.length === 1) {
        child = nameResult.rows[0];
      } else if (nameResult.rows.length > 1) {
        // Multiple children with same display name — PIN disambiguates
        for (const candidate of nameResult.rows) {
          if (await comparePassword(pin, candidate.pin)) {
            child = candidate;
            break;
          }
        }
        if (!child) {
          // Can't determine which child — record generic failure and return error
          // (no child_id to attach lockout to in this edge case)
          await db.query(
            'INSERT INTO login_attempt (identifier, ip_address, success) VALUES ($1, $2, false)',
            [normalizedInput, clientIp]
          );
          return res.status(401).json({ error: 'Felaktigt namn eller PIN-kod', attempts_remaining: null });
        }
      }
    }

    // If child not found at all — return generic error (don't reveal child existence)
    if (!child) {
      await db.query(
        'INSERT INTO login_attempt (identifier, ip_address, success) VALUES ($1, $2, false)',
        [normalizedInput, clientIp]
      );
      return res.status(401).json({ error: 'Felaktigt namn eller PIN-kod', attempts_remaining: null });
    }

    // ── Check existing lockout (DB-based, child_id scoped) ──────────────
    const lockoutStatus = await pinLockout.checkLockout(child.id);
    if (lockoutStatus.locked) {
      const minutes = lockoutStatus.lockout_minutes;
      const minuteText = minutes === 1 ? 'minut' : 'minuter';
      console.warn(
        `[PIN] Blocked attempt during lockout — child=${child.id} ip=${clientIp} ` +
        `locked_until=${lockoutStatus.locked_until}`
      );
      return res
        .set('Retry-After', String(lockoutStatus.retry_after_seconds))
        .status(429)
        .json({
          error: `Vänta en liten stund ⏰ Du kan försöka igen om ${minutes} ${minuteText}`,
          locked: true,
          retry_after: lockoutStatus.retry_after_seconds,
          locked_until: lockoutStatus.locked_until,
        });
    }

    // ── Validate PIN ──────────────────────────────────────────────────────
    const pinCorrect = await comparePassword(pin, child.pin);
    if (!pinCorrect) {
      // Record failure and get updated lockout state
      const updated = await pinLockout.recordFailedAttempt(child.id, clientIp);
      const attemptCount = updated.attempt_count;
      const attemptsRemaining = updated.attempts_remaining;

      // Also record in legacy login_attempt table
      await db.query(
        'INSERT INTO login_attempt (identifier, ip_address, success) VALUES ($1, $2, false)',
        [normalizedInput, clientIp]
      );

      // Audit
      pinLockout.auditLog(child.id, child.family_id, 'attempt_failed', clientIp, {
        attempt_count: attemptCount,
        lockout_minutes: updated.lockout_minutes,
      }).catch(() => {});

      // ── Parent notification at 3rd failed attempt ──────────────────────
      if (attemptCount === 3) {
        try {
          // In-app notification via system_messages (visible in parent dashboard)
          const msg = `${child.name} har försökt logga in med fel PIN-kod 3 gånger (${new Date().toLocaleTimeString('sv-SE', { hour: '2-digit', minute: '2-digit' })})`;
          await createSystemMessage(child.family_id, msg);
          await pinLockout.recordNotification(child.id, child.family_id, 'in_app');

          // Broadcast to any connected parents via SSE
          broadcast(child.family_id, 'PIN_FAILED_WARNING', { childId: child.id, childName: child.name, attemptCount });

          // Email cooldown check — max 1 email per child per N minutes
          const cooldownActive = await pinLockout.isEmailCooldownActive(child.id);
          if (!cooldownActive) {
            const parentResult = await db.query(
              `SELECT p.email FROM parent_child pc
               JOIN parent p ON p.id = pc.parent_id
               WHERE pc.child_id = $1
               ORDER BY pc.role = 'primary' DESC
               LIMIT 1`,
              [child.id]
            );
            if (parentResult.rows[0]?.email) {
              if (process.env.EMAIL_ENABLED !== 'false') {
                sendPinWarningEmail(parentResult.rows[0].email, child.name).catch(() => {});
              }
              await pinLockout.recordNotification(child.id, child.family_id, 'email');
              pinLockout.auditLog(child.id, child.family_id, 'parent_notified', clientIp, { channel: 'email' }).catch(() => {});
            }
          } else {
            pinLockout.auditLog(child.id, child.family_id, 'email_suppressed', clientIp, { reason: 'cooldown_active' }).catch(() => {});
          }
        } catch (notifyErr) {
          // Non-fatal — notification failure must not block the auth response
          console.error('[PIN] Parent notification error:', notifyErr);
        }
      }

      // ── New lockout triggered? ────────────────────────────────────────
      if (updated.lockout_minutes > 0) {
        const minutes = updated.lockout_minutes;
        const minuteText = minutes === 1 ? 'minut' : 'minuter';
        console.warn(
          `[PIN] Lockout triggered — child=${child.id} ip=${clientIp} ` +
          `attempts=${attemptCount} lockout=${minutes}min`
        );
        pinLockout.auditLog(child.id, child.family_id, 'lockout', clientIp, {
          lockout_minutes: minutes,
          attempt_count: attemptCount,
        }).catch(() => {});
        return res
          .set('Retry-After', String(minutes * 60))
          .status(429)
          .json({
            error: `Vänta en liten stund ⏰ Du kan försöka igen om ${minutes} ${minuteText}`,
            locked: true,
            retry_after: minutes * 60,
            locked_until: updated.locked_until,
          });
      }

      // ── Soft warning — attempts remaining ────────────────────────────
      let warningMessage;
      if (attemptsRemaining === 1) {
        warningMessage = `Nästan slut på försök! 1 försök kvar — fråga mamma eller pappa om du behöver hjälp 💛`;
      } else if (attemptsRemaining <= 2) {
        warningMessage = `Hmm, det var inte rätt PIN 🤔 Du har ${attemptsRemaining} försök kvar`;
      } else {
        warningMessage = `Felaktigt namn eller PIN-kod`;
      }

      return res.status(401).json({
        error: warningMessage,
        attempts_remaining: attemptsRemaining,
        attempt_count: attemptCount,
        max_attempts: pinLockout.MAX_ATTEMPTS,
      });
    }

    // ── Successful login ──────────────────────────────────────────────────
    await pinLockout.recordSuccessfulLogin(child.id);
    await db.query(
      'INSERT INTO login_attempt (identifier, ip_address, success) VALUES ($1, $2, true)',
      [normalizedInput, clientIp]
    );
    pinLockout.auditLog(child.id, child.family_id, 'attempt_success', clientIp, {}).catch(() => {});

    // Record login event for analytics
    db.query(
      'INSERT INTO login_event (user_id, role, family_id) VALUES ($1, $2, $3)',
      [child.id, 'child', child.family_id]
    ).catch(() => {});

    const accessToken = jwt.sign(
      { id: child.id, type: 'child', familyId: child.family_id, username: child.username, name: child.name },
      config.jwt.secret,
      { expiresIn: config.jwt.childExpiresIn }
    );

    // Issue 7-day refresh token — same as parent login.
    // Without this, child sessions cannot silently refresh and expire permanently
    // when the access token dies (8h for children).
    const rawRefresh = await createRefreshToken({
      userId: child.id,
      userType: 'child',
      familyId: child.family_id,
    });

    // ── Save parent session before overwriting cookies ─────────────────────
    // When a parent logs in as a child, their httpOnly tokens get overwritten.
    // Save them now so restoreParentSession middleware can restore the parent
    // view when the user navigates back to parent-facing pages.
    const parentAccessToken = req.cookies?.access_token;
    const parentRefreshToken = req.cookies?.refresh_token;
    if (parentAccessToken && parentRefreshToken) {
      try {
        const parentPayload = JSON.stringify({
          access_token: parentAccessToken,
          refresh_token: parentRefreshToken,
        });
        const encoded = Buffer.from(parentPayload).toString('base64');
        const maxAgeMs = 7 * 24 * 60 * 60 * 1000; // 7 days, same as refresh token
        res.cookie('stjarndag_parent_session', encoded, {
          httpOnly: true,
          secure: process.env.NODE_ENV === 'production',
          sameSite: 'lax',
          maxAge: maxAgeMs,
          path: '/',
        });
      } catch (saveErr) {
        // Non-fatal: parent session save failure must not block child login
        console.error('[AUTH] Parent session save failed:', saveErr.message);
      }
    }

    setRefreshCookie(res, rawRefresh);

    // Set access token as httpOnly cookie — XSS cannot read it.
    const expiresInSecs = parseDuration(config.jwt.childExpiresIn);
    setAccessCookie(res, accessToken, expiresInSecs);

    const csrfToken = generateCsrfToken(res);
    const user = { id: child.id, name: child.name, emoji: child.emoji, familyId: child.family_id, username: child.username, type: 'child' };
    // expiresAt lets the frontend schedule proactive silent refresh
    const expiresAt = Date.now() + expiresInSecs * 1000;
    return res.json({ csrfToken, user, expiresAt });

  } catch (err) {
    console.error('[AUTH] Child login error:', err);
    res.status(500).json({ error: 'Något gick fel. Försök igen senare.' });
  }
});

// ─── POST /api/auth/me/preferences ───────────────────────
// Update parent's preferred_view_mode. Only parents with active pedagog children can switch to 'pedagog'.
router.post('/me/preferences', requireAuth, async (req, res) => {
  try {
    if (req.user.type !== 'parent') {
      return res.status(400).json({ error: 'Endast föräldrar kan uppdatera visningsläge' });
    }
    const { preferredViewMode } = req.body || {};
    if (!preferredViewMode || !['parent', 'pedagog'].includes(preferredViewMode)) {
      return res.status(400).json({ error: 'preferredViewMode must be "parent" or "pedagog"' });
    }
    if (preferredViewMode === 'pedagog') {
      const roles = await getParentRoles(req.user.id);
      if (roles.pedagogChildIds.length === 0) {
        return res.status(400).json({ error: 'NO_PEDAGOG_ACCESS' });
      }
    }
    await db.query(
      'UPDATE parent SET preferred_view_mode = $2 WHERE id = $1',
      [req.user.id, preferredViewMode]
    );
    res.json({ success: true });
  } catch (err) {
    console.error('[AUTH] me/preferences error:', err);
    res.status(500).json({ error: 'Kunde inte spara inställningar' });
  }
});

// ─── GET /api/auth/me ─────────────────────────────────────
router.get('/me', requireAuth, async (req, res) => {
  try {
    if (req.user.type === 'parent') {
      const parentResult = await db.query(
        `SELECT p.id, p.email, p.family_id, p.is_admin, p.verified, p.created_at,
                COALESCE(p.onboarding_completed, true) as onboarding_completed,
                COALESCE(p.account_type, 'family') as account_type,
                COALESCE(p.preferred_view_mode, 'parent') as preferred_view_mode,
                f.is_lifetime_free,
                p.password_hash IS NOT NULL AS has_password,
                p.apple_user_id IS NOT NULL AS has_apple_linked,
                p.apple_email
         FROM parent p
         JOIN family f ON f.id = p.family_id
         WHERE p.id = $1`,
        [req.user.id]
      );
      if (parentResult.rows.length === 0) {
        return res.status(404).json({ error: 'Användare hittades inte' });
      }

      const parent = parentResult.rows[0];

      // Get parent roles (primary/shared vs pedagog-only)
      const roles = await getParentRoles(req.user.id);
      const hasPedagogChildren = roles.pedagogChildIds.length > 0;
      const isDualRole = roles.isDualRole;

      // Determine effective view mode — fallback to 'parent' if set to 'pedagog'
      // but no pedagog children remain (e.g., all pedagogen children unlinked)
      let effectiveViewMode = parent.preferred_view_mode;
      if (effectiveViewMode === 'pedagog' && roles.pedagogChildIds.length === 0) {
        effectiveViewMode = 'parent';
        // Sync account_type since pedagogen-only children are gone
        if (parent.account_type === 'educator') {
          await syncAccountType(req.user.id);
        }
      }

      // Get children via getChildrenForParent (revoked_at filtering applied there)
      const children = await getChildrenForParent(req.user.id, { allowedRoles: ['primary', 'shared'] });
      // Strip sensitive fields before sending to client
      for (const child of children) {
        delete child.pin;
        delete child.pin_fingerprint;
        delete child.pin_hint;
        delete child.pin_is_set;
      }

      return res.json({
        ...parent,
        isAdmin: !!parent.is_admin,
        account_type: parent.account_type,
        preferred_view_mode: effectiveViewMode,
        hasPedagogChildren,
        isDualRole,
        is_lifetime_free: parent.is_lifetime_free,
        accountAuth: {
          hasPassword: parent.has_password,
          hasAppleLinked: parent.has_apple_linked,
          email: parent.email,
          appleEmail: parent.apple_email || null,
          canUnlinkApple: parent.has_password && parent.has_apple_linked,
        },
        children,
      });
    }

    if (req.user.type === 'child') {
      const childResult = await db.query(
        `SELECT id, name, emoji, family_id, username, view_mode, timezone, birthday, created_at
         FROM child WHERE id = $1`,
        [req.user.id]
      );
      if (childResult.rows.length === 0) {
        return res.status(404).json({ error: 'Användare hittades inte' });
      }

      return res.json({ ...childResult.rows[0], type: 'child' });
    }

    res.status(400).json({ error: 'Okänd användartyp' });
  } catch (err) {
    console.error('[AUTH] Me error:', err);
    res.status(500).json({ error: 'Något gick fel. Försök igen senare.' });
  }
});

// ─── GET /api/auth/csrf-token ─────────────────────────────
// Returns a fresh CSRF token and sets it in a readable (non-httpOnly) cookie.
// Call this once on app init, then include X-CSRF-Token header on mutations.
router.get('/csrf-token', (req, res) => {
  const token = generateCsrfToken(res);
  res.json({ csrfToken: token });
});

// ─── POST /api/auth/refresh ───────────────────────────────
// Exchange a valid refresh token cookie for a new short-lived access token.
// The refresh token cookie is rotated (old one deleted, new one issued).
router.post('/refresh', async (req, res) => {
  try {
    const raw = req.cookies?.refresh_token;
    const row = await verifyRefreshToken(raw);

    if (!row) {
      clearRefreshCookie(res);
      return res.status(401).json({ error: 'Refresh-token ogiltig eller utgången' });
    }

    // Rotate refresh token — revoke old, issue new
    await revokeRefreshToken(raw);
    const newRaw = await createRefreshToken({
      userId: row.user_type === 'parent' ? row.parent_id : row.child_id,
      userType: row.user_type,
      familyId: row.family_id,
    });
    setRefreshCookie(res, newRaw);

    // Issue a new short-lived access token
    let accessToken;
    let accessExpiresSecs;
    if (row.user_type === 'parent') {
      const pr = await db.query(
        'SELECT id, family_id, email, is_admin FROM parent WHERE id = $1',
        [row.parent_id]
      );
      if (!pr.rows[0]) {
        clearRefreshCookie(res);
        return res.status(401).json({ error: 'Användare hittades inte' });
      }
      const p = pr.rows[0];
      accessToken = jwt.sign(
        { id: p.id, type: 'parent', familyId: p.family_id, email: p.email, isAdmin: p.is_admin },
        config.jwt.secret,
        { expiresIn: config.jwt.expiresIn }
      );
      accessExpiresSecs = parseDuration(config.jwt.expiresIn);
    } else {
      const cr = await db.query(
        'SELECT id, family_id, username, name FROM child WHERE id = $1',
        [row.child_id]
      );
      if (!cr.rows[0]) {
        clearRefreshCookie(res);
        return res.status(401).json({ error: 'Användare hittades inte' });
      }
      const c = cr.rows[0];
      accessToken = jwt.sign(
        { id: c.id, type: 'child', familyId: c.family_id, username: c.username, name: c.name },
        config.jwt.secret,
        { expiresIn: config.jwt.childExpiresIn }
      );
      accessExpiresSecs = parseDuration(config.jwt.childExpiresIn);
    }

    // Set access token as httpOnly cookie — XSS cannot read it.
    setAccessCookie(res, accessToken, accessExpiresSecs);

    // Refresh the CSRF cookie so it doesn't expire between silent refreshes.
    // The cookie has a 24h maxAge; without this, long-lived sessions lose CSRF protection.
    const csrfToken = generateCsrfToken(res);

    // expiresAt lets the frontend re-schedule the next silent refresh
    const expiresAt = Date.now() + accessExpiresSecs * 1000;
    res.json({ csrfToken, expiresAt });
  } catch (err) {
    console.error('[AUTH] Refresh error:', err);
    res.status(500).json({ error: 'Något gick fel. Försök igen senare.' });
  }
});

// ─── POST /api/auth/apple ────────────────────────────────
// Apple Sign In — verify JWT identity token against Apple's public keys,
// then create or link the parent account.
// Scenarios:
//   1. Existing Apple user (by apple_user_id) → 200 + session
//   2. New user (email not found) → 201 + session, lifetime_free tier
//   3. Existing password account (email found, no Apple link) → 409 + email_conflict
router.post('/apple', appleLoginLimiter, async (req, res) => {
  try {
    const { idToken, firstName, lastName } = req.body;
    if (!idToken || typeof idToken !== 'string') {
      return res.status(400).json({ error: 'idToken krävs' });
    }

    // Verify the JWT using Apple's public JWKS — never trust name/email from request body
    const appleUser = await verifyAppleIdToken(idToken);
    if (!appleUser) {
      return res.status(401).json({ error: 'Ogiltig Apple-identitetstoken' });
    }

    const { sub: appleUserId, email: appleEmail } = appleUser;

    // SCENARIO 1 — Existing Apple user: apple_user_id already linked → login directly
    const existingByApple = await parentDb.getParentByAppleUserId(appleUserId);
    if (existingByApple) {
      return completeLogin(req, res, existingByApple, 'parent');
    }

    // SCENARIO 3 — Account exists with password: email found but no Apple link → conflict
    if (appleEmail) {
      const existingByEmail = await parentDb.getParentByEmail(appleEmail);
      if (existingByEmail && existingByEmail.email && existingByEmail.has_password) {
        return res.status(409).json({
          error: 'email_conflict',
          email: appleEmail,
        });
      }
    }

    // SCENARIO 2 — New user: apple_user_id not linked and email not in DB
    const displayName = (firstName && lastName)
      ? `${firstName.trim()} ${lastName.trim()}`
      : (firstName?.trim() || appleEmail?.split('@')[0] || 'Förälder');

    const newParent = await createParentWithApple({
      appleUserId,
      appleEmail,
      displayName,
    });

    return completeLogin(req, res, newParent, 'parent');

  } catch (err) {
    console.error('[AUTH] Apple Sign In error:', err);
    res.status(500).json({ error: 'Något gick fel. Försök igen senare.' });
  }
});

// ─── POST /api/auth/apple/link ──────────────────────────
// Link an existing password-account to the current Apple ID.
// Requires the user to be logged in with a password account first.
router.post('/apple/link', appleLoginLimiter, async (req, res) => {
  try {
    const { idToken } = req.body;
    if (!idToken || typeof idToken !== 'string') {
      return res.status(400).json({ error: 'idToken krävs' });
    }

    // User must be authenticated via password (not Apple) to link
    if (!req.user || req.user.type !== 'parent') {
      return res.status(401).json({ error: 'Du måste vara inloggad för att länka Apple-konto' });
    }

    const appleUser = await verifyAppleIdToken(idToken);
    if (!appleUser) {
      return res.status(401).json({ error: 'Ogiltig Apple-identitetstoken' });
    }

    const { sub: appleUserId, email: appleEmail } = appleUser;

    // Check if Apple user ID already belongs to another account
    const existing = await parentDb.getParentByAppleUserId(appleUserId);
    if (existing && existing.id !== req.user.id) {
      return res.status(409).json({ error: 'Detta Apple-konto är redan linkat till ett annat konto' });
    }

    // Link the Apple ID to the current parent account
    await parentDb.linkAppleUserId(req.user.id, appleUserId, appleEmail || null);

    res.json({ message: 'Apple-konto länkat!' });
  } catch (err) {
    console.error('[AUTH] Apple link error:', err);
    res.status(500).json({ error: 'Något gick fel. Försök igen senare.' });
  }
});

// ─── Helper: verify Apple identity token against Apple's JWKS ───────
// Fetches Apple's public keys, caches them in-memory for 24h, then
// validates the RS256 JWT signature + issuer + audience claims.
const APPLE_JWKS_CACHE_TTL_MS = 24 * 60 * 60 * 1000;
let _appleJwksCache = { keys: null, fetchedAt: 0 };

async function _fetchAppleJwks() {
  const now = Date.now();
  if (_appleJwksCache.keys && (now - _appleJwksCache.fetchedAt) < APPLE_JWKS_CACHE_TTL_MS) {
    return _appleJwksCache.keys;
  }
  try {
    const res = await fetch('https://appleid.apple.com/auth/keys');
    if (!res.ok) throw new Error(`Apple JWKS HTTP ${res.status}`);
    const data = await res.json();
    _appleJwksCache = { keys: data.keys || [], fetchedAt: now };
    return _appleJwksCache.keys;
  } catch (err) {
    console.error('[AUTH] Apple JWKS fetch failed, using cached keys:', err.message);
    return _appleJwksCache.keys || [];
  }
}

function _jwkToPem(jwk) {
  if (!jwk || jwk.kty !== 'RSA') return null;
  return crypto.createPublicKey({ key: jwk, format: 'jwk' })
    .export({ type: 'spki', format: 'pem' });
}

async function verifyAppleIdToken(idToken) {
  const jwt = require('jsonwebtoken');
  const APPLE_ISSUER = 'https://appleid.apple.com';
  const APPLE_AUDIENCE = process.env.APPLE_CLIENT_ID || 'se.mystarday.app';

  try {
    const decoded = jwt.decode(idToken, { complete: true });
    if (!decoded) return null;

    const { kid, alg } = decoded.header;
    if (!kid || alg !== 'RS256') return null;

    const keys = await _fetchAppleJwks();
    const jwk = keys.find(k => k.kid === kid);
    if (!jwk) {
      console.error('[AUTH] Apple JWK kid not found:', kid);
      return null;
    }

    const pem = _jwkToPem(jwk);
    if (!pem) return null;

    const payload = jwt.verify(idToken, pem, {
      issuer: APPLE_ISSUER,
      audience: APPLE_AUDIENCE,
      algorithms: ['RS256'],
    });

    return payload;
  } catch (err) {
    console.error('[AUTH] Apple token verification failed:', err.message);
    return null;
  }
}

// ─── Helper: create a new parent account from Apple Sign In ────────
async function createParentWithApple({ appleUserId, appleEmail, displayName }) {
  const db = require('../lib/db');
  const { sendWelcomeEmail } = require('../lib/welcome-mailer');
  const { registerContact } = require('../lib/email');

  const client = await db.getClient();

  try {
    await client.query('BEGIN');

    const familyName = `${displayName}s familj`;

    const familyResult = await client.query(
      `INSERT INTO family (name, subscription_status, is_lifetime_free)
       VALUES ($1, 'none', true)
       RETURNING id`,
      [familyName]
    );
    const familyId = familyResult.rows[0].id;

    // Create parent with Apple — no password hash, verified=true (Apple is identity provider)
    // onboarding_completed = false so parent goes through the onboarding wizard
    const parentResult = await client.query(
      `INSERT INTO parent (family_id, email, password_hash, name, verified,
                          newsletter_subscribed, family_role, apple_user_id, apple_email, onboarding_completed)
       VALUES ($1, $2, NULL, $3, true, true, 'förälder', $4, $5, false)
       RETURNING id, family_id, email, name, verified, is_admin, created_at,
                 COALESCE(onboarding_completed, true) as onboarding_completed`,
      [familyId, appleEmail || `apple_${appleUserId}@privaterelay.appleid.com`, displayName, appleUserId, appleEmail]
    );
    const parent = parentResult.rows[0];

    // Seed default activities (same as regular registration)
    const defaultActivities = [
      { name: 'Vakna',           icon: '🛏️', category: 'Morgon',      star_value: 1, sort_order: 0, schema_type: 'forskola' },
      { name: 'Klä på sig',       icon: '🌟', category: 'Morgon',      star_value: 1, sort_order: 1, schema_type: 'forskola' },
      { name: 'Borsta tänderna',   icon: '🪥', category: 'Morgon',      star_value: 1, sort_order: 2, schema_type: 'forskola' },
      { name: 'Äta frukost',      icon: '🍳', category: 'Morgon',      star_value: 1, sort_order: 3, schema_type: 'forskola' },
      { name: 'Förskola/Skola',   icon: '🏫', category: 'Förmiddag',  star_value: 1, sort_order: 0, schema_type: 'forskola' },
      { name: 'Leka ute',         icon: '🛝', category: 'Förmiddag',  star_value: 1, sort_order: 1, schema_type: 'forskola' },
      { name: 'Pyssel',           icon: '🎨', category: 'Förmiddag',  star_value: 1, sort_order: 2, schema_type: 'forskola' },
      { name: 'Mellanmål',        icon: '🍎', category: 'Eftermiddag',star_value: 1, sort_order: 0, schema_type: 'forskola' },
      { name: 'Leka',             icon: '🧩', category: 'Eftermiddag',star_value: 1, sort_order: 1, schema_type: 'forskola' },
      { name: 'Träning/Aktivitet',icon: '🏃', category: 'Eftermiddag',star_value: 1, sort_order: 2, schema_type: 'forskola' },
      { name: 'Middag',           icon: '🍽️', category: 'Kväll',      star_value: 1, sort_order: 0, schema_type: 'forskola' },
      { name: 'Borsta tänderna (kväll)', icon: '🪥', category: 'Kväll',star_value: 1, sort_order: 1, schema_type: 'forskola' },
      { name: 'Pyjamas',          icon: '🧸', category: 'Kväll',      star_value: 1, sort_order: 2, schema_type: 'forskola' },
      { name: 'Godnattsaga',      icon: '📕', category: 'Kväll',      star_value: 1, sort_order: 3, schema_type: 'forskola' },
      { name: 'Sova',             icon: '😴', category: 'Kväll',      star_value: 1, sort_order: 4, schema_type: 'forskola' },
    ];
    const TEMPLATE_CATEGORIES = [
      { key: 'forskola', name: 'Förskola', sort_order: 0 },
      { key: 'morgon',   name: 'Morgon',   sort_order: 2 },
      { key: 'dag',      name: 'Dag',      sort_order: 3 },
      { key: 'kvall',    name: 'Kväll',    sort_order: 4 },
    ];
    const TIME_CATEGORY_OFFSET = { 'Morgon': 0, 'Förmiddag': 100, 'Eftermiddag': 200, 'Kväll': 300 };
    const CATEGORY_TO_TIME_GROUP = { 'Morgon': 'morgon', 'Förmiddag': 'formiddag', 'Eftermiddag': 'eftermiddag', 'Kväll': 'kvall' };

    const categoryMap = {};
    for (const cat of TEMPLATE_CATEGORIES) {
      const catResult = await client.query(
        'INSERT INTO category (family_id, name, sort_order, is_default) VALUES ($1, $2, $3, true) RETURNING id',
        [familyId, cat.name, cat.sort_order]
      );
      categoryMap[cat.key] = catResult.rows[0].id;
    }

    for (const act of defaultActivities) {
      const catId = categoryMap[act.schema_type];
      if (!catId) continue;
      const timeGroup = CATEGORY_TO_TIME_GROUP[act.category] || 'morgon';
      const timeOffset = TIME_CATEGORY_OFFSET[act.category] ?? 400;
      const combinedSort = timeOffset + (act.sort_order ?? 0);
      await client.query(
        `INSERT INTO activity_template (family_id, name, icon, category_id, star_value, is_favorite, time_group, schema_type, sort_order)
         VALUES ($1, $2, $3, $4, $5, false, $6, $7, $8)`,
        [familyId, act.name, act.icon, catId, act.star_value, timeGroup, act.schema_type, combinedSort]
      );
    }

    // Notification preferences
    await client.query('INSERT INTO notification_preference (parent_id) VALUES ($1)', [parent.id]);

    // Apple Sign In users get lifetime_free tier — no trial, no expiry.
    // These are among the inaugural 200 families who signed up via Apple.
    await client.query(
      `INSERT INTO family_subscriptions (family_id, tier, components)
       VALUES ($1, 'lifetime_free', $2)`,
      [familyId, JSON.stringify([{ component: 'basic_app', granted_at: new Date().toISOString(), expires_at: null }])]
    );

    await client.query('COMMIT');

    // Analytics: signup started
    require('../lib/analytics-tracker').trackSignupStarted(familyId);

    // Register contact FIRST so emails are accepted by the proxy (no cold outreach block)
    if (appleEmail) {
      await registerContact(appleEmail, displayName, 'signup').catch(err => {
        console.error('[AUTH] registerContact failed for', appleEmail, ':', err.message);
      });
      // Welcome email (fire-and-forget)
      const { hasAccess } = require('../../db/features');
      const welcomeEmailAllowed = await hasAccess(familyId, 'valkomstmail');
      if (welcomeEmailAllowed) {
        sendWelcomeEmail(appleEmail, parent.id, { foralderns_namn: displayName, barnets_namn: '' }).catch(err => {
          console.error('[AUTH] Welcome email send failed for', appleEmail, ':', err.message);
        });
      }
    }

    return parent;

  } catch (err) {
    await client.query('ROLLBACK');
    throw err;
  } finally {
    client.release();
  }
}

// ─── Helper: complete login for a parent record ───────────────────
async function completeLogin(req, res, parent, userType) {
  // WHY: All modules already imported at top of file — but duplicated
  // here to keep the helper self-contained and avoid closure surprises.

  // Record login event for analytics
  db.query(
    'INSERT INTO login_event (user_id, role, family_id) VALUES ($1, $2, $3)',
    [parent.id, userType, parent.family_id]
  ).catch(() => {});

  const accessToken = jwt.sign(
    {
      id: parent.id,
      type: userType,
      familyId: parent.family_id,
      email: parent.email || null,
      isAdmin: parent.is_admin || false,
    },
    config.jwt.secret,
    { expiresIn: config.jwt.expiresIn }
  );

  const rawRefresh = await createRefreshToken({
    userId: parent.id,
    userType,
    familyId: parent.family_id,
  });
  setRefreshCookie(res, rawRefresh);

  const expiresInSecs = typeof config.jwt.expiresIn === 'string'
    ? parseDuration(config.jwt.expiresIn)
    : config.jwt.expiresIn;
  setAccessCookie(res, accessToken, expiresInSecs);

  const csrfToken = generateCsrfToken(res);

  const user = {
    id: parent.id,
    email: parent.email || null,
    familyId: parent.family_id,
    isAdmin: parent.is_admin || false,
    type: userType,
    onboarding_completed: parent.onboarding_completed,
  };

  const expiresAt = Date.now() + expiresInSecs * 1000;
  res.json({ csrfToken, user, expiresAt });
}

// ─── POST /api/auth/logout ────────────────────────────────
// Revoke the refresh token and clear cookies.
// When a child logs out, if a parent session was saved (via stjarndag_parent_session),
// restore it so the parent remains logged in.
router.post('/logout', async (req, res) => {
  try {
    const raw = req.cookies?.refresh_token;
    if (raw) {
      await revokeRefreshToken(raw);
    }
    // Explicitly clear access_token with exact matching attributes (path, secure, sameSite).
    // Using res.clearCookie directly (not clearAccessCookie) as a belt-and-suspenders approach
    // to ensure the cookie is deleted even if the helper has a subtle mismatch.
    res.clearCookie('access_token', {
      httpOnly: true,
      secure: process.env.NODE_ENV === 'production',
      sameSite: 'lax',
      path: '/',
    });
    res.clearCookie('refresh_token', {
      httpOnly: true,
      secure: process.env.NODE_ENV === 'production',
      sameSite: 'lax',
      path: '/api/auth',
    });
    // Clear CSRF cookie too
    res.clearCookie('csrf_token', { path: '/' });

    // ── Restore parent session only if CHILD is logging out ────────────────
    // Always decode access token from cookie to determine who is logging out.
    // Only restore the parent session when the child (not the parent) logs out.
    const accessTokenStr = req.headers.cookie?.split(';').find(c => c.trim().startsWith('access_token='))?.split('=').slice(1).join('=');
    const decoded = accessTokenStr ? jwt.decode(accessTokenStr) : null;
    if (decoded?.type !== 'child') {
      // Parent logout (or unknown type) — clear parent session cookie and do full logout
      res.clearCookie('stjarndag_parent_session', { path: '/' });
      return res.json({ message: 'Utloggad' });
    }

    const parentSessionCookie = req.cookies?.stjarndag_parent_session;
    if (parentSessionCookie) {
      let session;
      try {
        session = JSON.parse(Buffer.from(parentSessionCookie, 'base64').toString('utf8'));
      } catch {
        // Invalid cookie — just clear it
        res.clearCookie('stjarndag_parent_session', { path: '/' });
        return res.json({ message: 'Utloggad' });
      }

      if (session?.access_token && session?.refresh_token) {
        // Check if family has parent PIN — if so, keep session but require PIN first.
        // The frontend will show the PIN overlay before calling restore-parent-session.
        try {
          const familyResult = await db.query(
            'SELECT parent_pin_hash IS NOT NULL AS has_pin FROM family WHERE id = $1',
            [decoded.familyId]
          );
          if (familyResult.rows[0]?.has_pin) {
            // Parent PIN set — return needsParentPin: true so frontend shows PIN overlay.
            // Keep the parent session cookie intact (don't clear it).
            return res.json({ message: 'Utloggad', needsParentPin: true });
          }
        } catch (err) {
          console.error('[AUTH] Logout: parent-pin check failed:', err.message);
          // On error, fall through to auto-restore (favor usability)
        }

        // No parent PIN → auto-restore parent session
        res.cookie('access_token', session.access_token, {
          httpOnly: true,
          secure: process.env.NODE_ENV === 'production',
          sameSite: 'lax',
          maxAge: 15 * 60 * 1000,
          path: '/',
        });
        res.cookie('refresh_token', session.refresh_token, {
          httpOnly: true,
          secure: process.env.NODE_ENV === 'production',
          sameSite: 'lax',
          maxAge: 7 * 24 * 60 * 60 * 1000,
          path: '/api/auth',
        });
        res.clearCookie('stjarndag_parent_session', { path: '/' });
        return res.json({ message: 'Utloggad', sessionRestored: true });
      }
    }

    res.clearCookie('stjarndag_parent_session', { path: '/' });
    res.json({ message: 'Utloggad' });
  } catch (err) {
    console.error('[AUTH] Logout error:', err);
    // Still clear cookies even on error
    res.clearCookie('access_token', {
      httpOnly: true,
      secure: process.env.NODE_ENV === 'production',
      sameSite: 'lax',
      path: '/',
    });
    res.clearCookie('refresh_token', {
      httpOnly: true,
      secure: process.env.NODE_ENV === 'production',
      sameSite: 'lax',
      path: '/api/auth',
    });
    res.clearCookie('csrf_token', { path: '/' });
    res.clearCookie('stjarndag_parent_session', { path: '/' });
    res.json({ message: 'Utloggad' });
  }
});

module.exports = router;
