"""Runtime definitions for WORLD_ENGINE v1.0."""
from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class RuntimeSpec:
    id: str
    name: str
    purpose: str
    responsibilities: list[str]
    public_api: list[str]
    events_emits: list[str]
    events_subscribes: list[str]
    inputs: list[str]
    outputs: list[str]
    data_contracts: list[str]
    state: str
    lifecycle: list[str]
    performance_budget: str
    accessibility: list[str]
    testing_strategy: list[str]
    extension_points: list[str]
    anti_patterns: list[str]
    definition_of_done: list[str]


def _rt(
    id: str,
    name: str,
    purpose: str,
    responsibilities: list[str],
    public_api: list[str],
    events_emits: list[str],
    events_subscribes: list[str],
    inputs: list[str],
    outputs: list[str],
    data_contracts: list[str],
    lifecycle: str,
    performance_budget: str | list[str],
    accessibility: list[str],
    testing_strategy: list[str],
    extension_points: list[str],
    anti_patterns: list[str],
    definition_of_done: list[str],
) -> RuntimeSpec:
    phases = [p.strip() for p in lifecycle.replace("->", "→").split("→") if p.strip()]
    state = phases[0] if phases else "Active"
    pb = performance_budget if isinstance(performance_budget, str) else "; ".join(performance_budget)
    return RuntimeSpec(
        id=id,
        name=name,
        purpose=purpose,
        responsibilities=responsibilities,
        public_api=public_api,
        events_emits=events_emits,
        events_subscribes=events_subscribes,
        inputs=inputs,
        outputs=outputs,
        data_contracts=data_contracts,
        state=state,
        lifecycle=phases,
        performance_budget=pb,
        accessibility=accessibility,
        testing_strategy=testing_strategy,
        extension_points=extension_points,
        anti_patterns=anti_patterns,
        definition_of_done=definition_of_done,
    )


ALL_RUNTIMES: list[RuntimeSpec] = [
    _rt(
        "core",
        "Core Runtime",
        "Age-agnostic orchestrator: boot, tick loop, runtime registry, global event routing, pack binding, and session boundary. Owns no fiction.",
        [
            "Initialize engine from manifest + pack",
            "Register and wire all sub-runtimes",
            "Drive fixed-timestep simulation tick (60 FPS target)",
            "Route cross-runtime messages via Event Bus and Message Bus",
            "Enforce Constitution §6 — reject magic-number thresholds at load",
            "Expose hooks: onActivityComplete, onWorldEnter, onMilestone (GDB Appendix B)",
        ],
        [
            "engine.initialize(manifest, pack_id, session)",
            "engine.tick(delta_ms)",
            "engine.pause() / engine.resume()",
            "engine.shutdown()",
            "engine.getRuntime(name)",
            "engine.emit(event_name, payload)",
            "engine.subscribe(event_name, handler_id)",
        ],
        ["engine.ready", "engine.tick", "engine.error", "engine.shutdown"],
        ["* (all runtimes may subscribe to engine lifecycle)"],
        ["World Manifest", "Experience Pack manifest", "Session token", "Device profile"],
        ["Runtime graph state", "Active tick budget report"],
        ["EngineState", "SessionContext", "RuntimeRegistry"],
        "Cold → Loading → Ready → Running → Paused → ShuttingDown → Terminated",
        "Boot to first interactive frame ≤1500 ms mobile; tick orchestration overhead ≤2 ms/frame",
        ["Reduced motion propagates to all runtimes on init", "No age-specific branching in core"],
        ["Contract tests: manifest load", "Integration: tick with all runtimes stubbed", "No age if-statements lint gate"],
        ["Plugin runtime slots", "Custom tick phases via manifest"],
        ["Hardcoded child copy", "Age if-statements", "Fiction in core", "Magic unlock constants"],
        ["QG-006–008 pass", "CTO architecture review 10/10", "All runtimes register without fork"],
    ),
    _rt(
        "world",
        "World Runtime",
        "Load and manage one Experience Pack world instance: slug, emotion job, progression manifest binding, world graph root.",
        [
            "Parse World Manifest (world.yaml / world.json)",
            "Mount World Graph root node",
            "Bind Progression Runtime to world progression map",
            "Coordinate region load/unload",
            "Emit onWorldEnter / onWorldExit",
        ],
        [
            "world.load(manifest_ref)",
            "world.unload()",
            "world.getRegion(region_id)",
            "world.getProgressionState()",
            "world.resolveUnlockSignal(signal)",
        ],
        ["world.loaded", "world.unloaded", "world.progression_changed"],
        ["progression.node_unlocked", "pack.config_changed", "save.world_state_restored"],
        ["World Manifest", "Pack progression map", "Server world state snapshot"],
        ["Active world graph", "Progression overlay"],
        ["WorldManifest", "WorldState", "WorldGraphRoot"],
        "Unloaded → Loading → Active → Suspending → Unloaded",
        ["World swap ≤800 ms with cached assets", "Memory cap per world configurable in manifest"],
        ["World entry never blocks Idag spine", "One primary interaction default per WDB"],
        ["Manifest validation against schema", "Load test all v1 worlds", "Differentiation matrix spot check"],
        ["Append-only progression nodes", "Future world slots without engine change"],
        ["Fixed part count assumptions", "Hardcoded world slug lists in engine", "Cross-world fiction bleed"],
        ["WQS world subset pass", "Manifest validates", "GDB world mapping aligned"],
    ),
    _rt(
        "region",
        "Region Runtime",
        "Spatial partition within a world: outdoor, indoor wing, pier section. Owns Region Graph subtree.",
        [
            "Load region definition and scene list",
            "Stream adjacent regions lazily",
            "Apply region-level weather/season/lighting overrides",
            "Manage region enter/exit transitions",
        ],
        [
            "region.load(region_id)",
            "region.unload()",
            "region.getScene(scene_id)",
            "region.setActive(active: bool)",
        ],
        ["region.entered", "region.exited", "region.streamed"],
        ["weather.changed", "season.changed", "camera.transition_requested"],
        ["Region definition", "World Graph edge", "Asset bundle refs"],
        ["Region Graph", "Streaming state"],
        ["RegionManifest", "RegionGraph", "RegionState"],
        "Dormant → Loading → Active → Streaming → Unloaded",
        ["Region stream budget ≤200 ms on 4G", "Max 2 active regions mobile default"],
        ["Region transitions respect reduced motion", "No mandatory region for routine completion"],
        ["Region graph acyclic validation", "Streaming simulation tests"],
        ["Procedural region expansion via manifest", "Multi-floor regions"],
        ["Loading entire world at once", "Region blocking tap path"],
        ["Region schema validates", "LOD hooks declared"],
    ),
    _rt(
        "scene",
        "Scene Runtime",
        "Single diorama frame: entities, layers, interactables, ambient life. Scene Graph owner.",
        [
            "Instantiate Scene Graph from manifest",
            "Run idle simulation layers (Living World)",
            "Route input to Interaction Runtime",
            "Manage scene lifecycle and entity spawn/despawn",
        ],
        [
            "scene.load(scene_id)",
            "scene.unload()",
            "scene.getEntity(entity_id)",
            "scene.queryAABB(bounds)",
            "scene.setLayerVisibility(layer_id, visible)",
        ],
        ["scene.loaded", "scene.unloaded", "scene.entity_spawned", "scene.entity_despawned"],
        ["interaction.completed", "animation.completed", "progression.node_unlocked"],
        ["Scene Manifest", "Entity templates", "Progression visibility rules"],
        ["Scene Graph", "Active entity set"],
        ["SceneManifest", "SceneGraph", "SceneState"],
        "Empty → Building → Active → TearingDown → Empty",
        ["≤16 ms frame budget for scene simulation on target devices", "Max entities configurable per scene manifest"],
        ["48 px minimum touch targets", "Reduced motion disables non-essential ambient"],
        ["Scene graph snapshot tests", "Interaction path reachability"],
        ["Dynamic scene layers", "Cutscene scenes via manifest"],
        ["Frozen diorama >5 s", "Blocking modal on scene entry"],
        ["One focal frame per world entry (WDB)", "Idle motion ≥1 layer"],
    ),
    _rt(
        "interaction",
        "Interaction Runtime",
        "Data-driven gesture and verb system: tap, drag, build, feed, etc. Interaction Graph executor.",
        [
            "Map input events to interaction verbs via manifest",
            "Execute Interaction Graph nodes (preconditions → actions → effects)",
            "Gate interactions by progression state",
            "Emit completion events to Progression and Analytics",
        ],
        [
            "interaction.registerVerb(verb_def)",
            "interaction.tryStart(target_id, verb, gesture_context)",
            "interaction.cancel(session_id)",
            "interaction.getAvailableVerbs(entity_id)",
        ],
        ["interaction.started", "interaction.completed", "interaction.failed", "interaction.cancelled"],
        ["input.gesture", "progression.node_unlocked", "npc.dialog_closed"],
        ["Interaction Manifest", "Gesture context", "Entity capability tags"],
        ["Interaction session state", "Effect queue"],
        ["InteractionManifest", "InteractionGraph", "InteractionSession"],
        "Idle → Targeting → Active → Resolving → Idle",
        ["Input-to-feedback ≤100 ms", "One primary interaction default per scene"],
        ["All verbs completable without sound", "Hold gestures have cancel path"],
        ["Verb matrix regression", "Gesture simulator tests", "No soft-lock paths"],
        ["New verbs via manifest only", "Future gesture types via Gesture System extension"],
        ["Hardcoded tap-only", "Interaction requiring network", "Blame copy on failure"],
        ["Full verb registry documented", "Anti-frustration: back always exits"],
    ),
    _rt(
        "progression",
        "Progression Runtime",
        "Progression Node resolver: unlock signals, emotional beats, no magic numbers (Constitution §6, WDB §2).",
        [
            "Load progression map from pack manifest",
            "Evaluate unlock_signal rules against engine events",
            "Track node state per child (server truth)",
            "Reveal nodes in scene without quota UI",
        ],
        [
            "progression.loadMap(world_slug, map_ref)",
            "progression.evaluateEvent(event)",
            "progression.isUnlocked(node_id)",
            "progression.getVisibleNodes(scene_id)",
            "progression.unlock(node_id, metadata)",
        ],
        ["progression.node_unlocked", "progression.phase_changed", "progression.milestone_reached"],
        ["onActivityComplete", "onStarGranted", "onMilestone", "interaction.completed"],
        ["Progression map JSON", "Pack config keys", "Server child progression rows"],
        ["Node unlock table", "Phase index"],
        ["ProgressionMap", "ProgressionNode", "ProgressionState"],
        "Uninitialized → Loaded → Active → Syncing → Active",
        ["Rule evaluation ≤5 ms per event", "No O(n²) scan over full history"],
        ["Progress never shown as guilt counter", "No fixed X of Y parts UI"],
        ["Golden-path unlock tests per world", "ADR trigger on >20% node count change"],
        ["New progression models per world via manifest", "Cross-world progression hooks"],
        ["PARTS_REQUIRED = 75", "Stars hardcoded thresholds in engine", "Level caps in code"],
        ["Constitution §6 compliance", "WDB node schema match"],
    ),
    _rt(
        "npc",
        "NPC Runtime",
        "Non-player characters: memory, mood, schedule, personality, relationships, dialog, idle, reactions.",
        [
            "Instantiate NPCs from manifest",
            "Run NPC Schedule against world clock",
            "Manage mood and memory decay/recovery",
            "Route dialog through Interaction Runtime",
            "Play NPC Animation states",
        ],
        [
            "npc.spawn(npc_id)",
            "npc.despawn(npc_id)",
            "npc.getState(npc_id)",
            "npc.triggerReaction(npc_id, stimulus)",
            "npc.startDialog(npc_id, dialog_tree_id)",
        ],
        ["npc.spawned", "npc.mood_changed", "npc.dialog_line", "npc.reaction_played"],
        ["interaction.inspect", "progression.node_unlocked", "weather.changed", "season.changed"],
        ["NPC Manifest", "Dialog trees", "Schedule tables"],
        ["NPC state per instance"],
        ["NPCManifest", "NPCState", "NPCMemory", "NPCSchedule"],
        "Absent → Spawning → Idle → Engaged → Reacting → Idle",
        ["Max active NPCs per scene from manifest", "Dialog advance ≤1 tap default"],
        ["NPC never guilt-trip on miss days", "Dialog skippable"],
        ["Personality consistency tests", "Schedule overlap validation"],
        ["New NPC types via manifest", "Relationship graph expansion"],
        ["Tamagotchi neglect mechanics", "Random guilt dialog", "Blocking NPC on routine path"],
        ["PCB NPC contract aligned", "G-rules pass"],
    ),
    _rt(
        "behaviour",
        "Behaviour Runtime",
        "Behaviour Tree and State Machine execution for entities, props, ambient life.",
        [
            "Load behaviour trees from manifest",
            "Tick active behaviours within budget",
            "Transition state machines on events",
            "Coordinate with Animation Runtime for outputs",
        ],
        [
            "behaviour.attach(entity_id, tree_ref)",
            "behaviour.detach(entity_id)",
            "behaviour.sendSignal(entity_id, signal)",
            "behaviour.getBlackboard(entity_id)",
        ],
        ["behaviour.state_entered", "behaviour.state_exited", "behaviour.tree_completed"],
        ["engine.tick", "interaction.completed", "npc.mood_changed"],
        ["Behaviour Manifest", "Blackboard schema"],
        ["Active behaviour instances"],
        ["BehaviourTree", "StateMachine", "Blackboard"],
        "Inactive → Running → Suspended → Completed",
        ["Behaviour tick share ≤4 ms/frame aggregate", "Tree depth cap in manifest"],
        ["Behaviours respect reduced motion flag", "No seizure-inducing loops"],
        ["Tree unit tests with fixtures", "State coverage matrix"],
        ["Custom node types via manifest registry", "Parallel subtree execution"],
        ["Behaviours in code only", "Infinite loops without timeout"],
        ["Living world idle rules satisfied", "Micro-event budget enforced"],
    ),
    _rt(
        "animation",
        "Animation Runtime",
        "Animation Graph playback: skeletal, sprite, procedural. Art Bible timing compliance.",
        [
            "Load animation clips and graphs from manifest",
            "Blend states on entity signals",
            "Honor celebration ≤2000 ms (Art Bible / GDB)",
            "Pool animation instances",
        ],
        [
            "animation.play(entity_id, clip_or_graph, options)",
            "animation.stop(entity_id, layer)",
            "animation.crossfade(entity_id, from, to, ms)",
            "animation.setSpeed(entity_id, factor)",
        ],
        ["animation.started", "animation.completed", "animation.loop"],
        ["behaviour.state_entered", "interaction.started", "progression.node_unlocked"],
        ["Animation Manifest", "Reduced motion flag"],
        ["Active playback layers"],
        ["AnimationGraph", "AnimationClip", "AnimationState"],
        "Idle → Playing → Blending → Idle",
        ["Celebration clips ≤2000 ms", "Blend ops ≤2 ms each"],
        ["Reduced motion: instant or shortened paths", "Skippable celebrations"],
        ["Timing token regression vs Art Bible", "Pool exhaustion tests"],
        ["Procedural layers via manifest curves", "IK extensions"],
        ["Hardcoded celebration duration in code", "Non-skippable 3s+ blocking anims"],
        ["Art Bible § motion tokens referenced", "Skip path exists"],
    ),
    _rt(
        "particle",
        "Particle Runtime",
        "Lightweight VFX: confetti bursts, dust, sparkles. Particle Graph driven.",
        [
            "Spawn particle systems from manifest",
            "Respect reduced motion (static or off)",
            "Pool emitters",
            "Cap simultaneous systems per scene",
        ],
        [
            "particle.emit(system_id, at_transform)",
            "particle.stop(system_id)",
            "particle.setGlobalEnabled(enabled)",
        ],
        ["particle.started", "particle.finished"],
        ["progression.node_unlocked", "interaction.celebrate"],
        ["Particle Manifest", "Performance tier"],
        ["Active emitter pool"],
        ["ParticleGraph", "ParticleSystem"],
        "Pooled → Active → Recycling",
        ["Max 3 concurrent celebration systems mobile", "GPU/CPU budget ≤1 ms/frame"],
        ["Off or static under reduced motion", "No >3 Hz flash"],
        ["Tier downgrade on low battery", "Pool reuse tests"],
        ["New systems via manifest only"],
        ["Full-screen particle blocking input", "Infinite emitters"],
        ["GDB celebration philosophy aligned"],
    ),
    _rt(
        "audio",
        "Audio Runtime",
        "Audio Graph: ambient, SFX, optional voice. Silent by default (Design System 06A).",
        [
            "Load audio banks lazily",
            "Mix layers with user mute prefs",
            "Spatial audio optional per scene",
            "No autoplay on child launch",
        ],
        [
            "audio.play(event_id, options)",
            "audio.stop(channel)",
            "audio.setMuted(muted)",
            "audio.preload(bank_ref)",
        ],
        ["audio.started", "audio.ended", "audio.load_failed"],
        ["scene.loaded", "interaction.completed", "weather.changed"],
        ["Audio Manifest", "User preferences"],
        ["Channel mixer state"],
        ["AudioGraph", "AudioEvent", "AudioBank"],
        "Silent → Loading → Ready → Playing",
        ["Audio decode async", "Max 2 simultaneous SFX mobile default"],
        ["Complete path without sound", "No notification spam"],
        ["Silent completion E2E", "Lazy load timing"],
        ["Voice packs per Experience Pack", "Dynamic mixing buses"],
        ["Autoplay on launch", "Required audio for progression"],
        ["Design System 06A compliance"],
    ),
    _rt(
        "camera",
        "Camera Runtime",
        "Camera Graph: framing, follow, transitions. One focal frame per world entry.",
        [
            "Apply camera rigs from manifest",
            "Smooth transitions between scene anchors",
            "Respect reduced motion (cut vs pan)",
            "Never trap player — back always works",
        ],
        [
            "camera.setRig(rig_id)",
            "camera.transitionTo(anchor_id, style)",
            "camera.shake(intensity, ms)",
            "camera.reset()",
        ],
        ["camera.transition_started", "camera.transition_completed"],
        ["scene.loaded", "interaction.started", "region.entered"],
        ["Camera Manifest", "Accessibility motion pref"],
        ["Active rig and blend state"],
        ["CameraGraph", "CameraRig", "CameraAnchor"],
        "Idle → Transitioning → Locked → Idle",
        ["Transition ≤400 ms default", "No camera update >8 ms"],
        ["Reduced motion uses cut", "Shake disabled under a11y"],
        ["Transition graph tests", "No soft-lock camera paths"],
        ["Cinematic rails via manifest", "Split-screen future"],
        ["Forced camera lock without exit", "Motion sickness patterns"],
        ["WDB focal frame rule"],
    ),
    _rt(
        "lighting",
        "Lighting Runtime",
        "Lighting Graph: time-of-day, region mood, progression reveals.",
        [
            "Apply lighting presets from manifest",
            "Blend on season/weather/phase",
            "Support progression-driven lamp reveals",
        ],
        [
            "lighting.applyPreset(preset_id)",
            "lighting.blend(from, to, factor)",
            "lighting.setPhase(phase_id)",
        ],
        ["lighting.changed"],
        ["season.changed", "weather.changed", "progression.node_unlocked"],
        ["Lighting Manifest"],
        ["Active preset stack"],
        ["LightingGraph", "LightingPreset"],
        "Default → Blending → Stable",
        ["Lighting eval ≤2 ms/frame", "Max 3 dynamic lights mobile"],
        ["Contrast maintained for readability", "No flashing lights"],
        ["Preset snapshot tests"],
        ["Per-world color scripts via manifest"],
        ["Hardcoded world palettes in engine"],
        ["Art Bible lighting handoff"],
    ),
    _rt(
        "weather",
        "Weather Runtime",
        "Weather Graph: rain, snow, wind sway. Max opacity ≤55% (WDB).",
        [
            "Resolve weather state from manifest + schedule",
            "Drive ambient audio and particle hooks",
            "Apply wind sway amplitudes to tagged entities",
        ],
        [
            "weather.setState(state_id)",
            "weather.getState()",
            "weather.transitionTo(state_id, duration_ms)",
        ],
        ["weather.changed", "weather.transition_completed"],
        ["season.changed", "engine.tick"],
        ["Weather Manifest", "World schedule"],
        ["Current weather state"],
        ["WeatherGraph", "WeatherState"],
        "Clear → Active → Transitioning",
        ["Weather overlay ≤55% opacity", "Sim cost ≤1 ms/frame"],
        ["Weather never blocks primary tap path"],
        ["Transition tests", "Opacity cap enforcement"],
        ["Regional weather overrides"],
        ["RNG weather blocking progression"],
        ["WDB living world weather rule"],
    ),
    _rt(
        "season",
        "Season Runtime",
        "Seasonal prop swaps and palette shifts. Max 2 props swap (WDB).",
        [
            "Map calendar to season phase via pack config",
            "Swap prop sets per manifest",
            "Year-round access — no lockout FOMO",
        ],
        [
            "season.setPhase(phase_id)",
            "season.getPhase()",
            "season.applyPropSwaps()",
        ],
        ["season.changed"],
        ["engine.tick", "pack.config_changed"],
        ["Season Manifest", "Calendar config"],
        ["Active season phase"],
        ["SeasonGraph", "SeasonPhase"],
        "Default → Active",
        ["Prop swap ≤100 ms", "Max 2 props per WDB"],
        ["Seasonal changes never punish miss days"],
        ["Swap count validation"],
        ["Hemisphere config per pack"],
        ["Seasonal FOMO countdown"],
        ["GDB season ethics"],
    ),
    _rt(
        "physics",
        "Physics Runtime (lightweight)",
        "Optional lightweight physics: drop, stack, balance verbs. Not a full rigid-body sim.",
        [
            "AABB overlap and simple gravity for tagged entities",
            "Support stack/balance interaction verbs",
            "Disable on low tier devices via manifest",
        ],
        [
            "physics.enable(scope)",
            "physics.step(delta_ms)",
            "physics.queryOverlap(aabb)",
        ],
        ["physics.collision", "physics.settled"],
        ["interaction.drop", "interaction.stack"],
        ["Physics Manifest", "Performance tier"],
        ["Active body set"],
        ["PhysicsBody", "PhysicsWorld"],
        "Off → Active → Sleeping",
        ["≤2 ms/frame when enabled", "Auto-sleep settled bodies"],
        ["No physics-required progression"],
        ["Verb integration tests"],
        ["Full physics engine plug-in boundary"],
        ["Full Box2D for all entities", "Physics blocking routine"],
        ["Optional per interaction manifest"],
    ),
    _rt(
        "save",
        "Save Runtime",
        "Offline-first local persistence + server authority. Save Graph orchestration.",
        [
            "Auto-save on completion events (GDB §43)",
            "Local snapshot for offline world view",
            "Versioned save format with migration path",
            "Compression and delta encoding",
        ],
        [
            "save.capture(scope)",
            "save.restore(snapshot_id)",
            "save.getLocalSnapshot()",
            "save.migrate(from_version, to_version)",
        ],
        ["save.captured", "save.restored", "save.migration_applied"],
        ["progression.node_unlocked", "interaction.completed", "onActivityComplete"],
        ["Save Graph manifest", "Server authoritative state"],
        ["Local snapshot store"],
        ["SaveGraph", "SaveSnapshot", "SaveVersion"],
        "Idle → Capturing → Persisted → Restoring",
        ["Save write async ≤50 ms blocking", "Snapshot size budget per child"],
        ["No manual save child UI", "Data survives app kill"],
        ["Migration golden files", "Rollback tests"],
        ["New scopes via manifest"],
        ["Blocking save spinners on Idag", "Client-only star grants"],
        ["GDB QG-438–440"],
    ),
    _rt(
        "sync",
        "Sync Runtime",
        "Delta sync, conflict resolution, server wins with merge log (GDB §43).",
        [
            "Queue offline operations with timestamp",
            "Delta sync on reconnect",
            "Resolve conflicts — server authoritative",
            "Calm retry with exponential backoff",
        ],
        [
            "sync.enqueue(operation)",
            "sync.flush()",
            "sync.getPendingCount()",
            "sync.resolveConflict(local, remote)",
        ],
        ["sync.started", "sync.completed", "sync.conflict", "sync.failed"],
        ["network.online", "save.captured"],
        ["Pending operation queue", "Server API responses"],
        ["Sync queue state", "Merge log"],
        ["SyncGraph", "SyncOperation", "MergeLogEntry"],
        "Idle → Queuing → Syncing → Idle",
        ["Background sync only", "No blocking Idag"],
        ["Sync indicator calm not alarm", "Errors never blame child"],
        ["Conflict simulation tests", "Offline queue E2E"],
        ["CRDT zones for cosmetic-only state future"],
        ["Data loss on conflict", "False celebration offline"],
        ["GDB QG-441–442"],
    ),
    _rt(
        "asset",
        "Asset Runtime",
        "Load, cache, stream, pool, LOD. Asset Graph and bundle management.",
        [
            "Resolve asset refs from manifest",
            "Lazy load and stream bundles",
            "Cache with LRU and disk persistence",
            "LOD tier selection by Performance Runtime",
        ],
        [
            "asset.load(ref, priority)",
            "asset.release(ref)",
            "asset.preload(bundle_id)",
            "asset.getLoadState(ref)",
        ],
        ["asset.loaded", "asset.failed", "asset.evicted"],
        ["scene.load", "region.streamed"],
        ["Asset Manifest", "CDN/base URL config"],
        ["Cache index", "In-flight loads"],
        ["AssetManifest", "AssetBundle", "AssetHandle"],
        "Cold → Loading → Ready → Evicted",
        ["First world LCP budget", "Memory cap configurable"],
        ["Alt text for narrative assets where applicable"],
        ["Corrupt bundle handling", "Cache hit rate metrics"],
        ["Hot-swappable asset packs"],
        ["Load entire world upfront", "Uncached blocking loads on tap"],
        ["Mobile-first lazy loading"],
    ),
    _rt(
        "pack",
        "Pack Runtime",
        "Experience Pack loader: fiction, copy, pacing, UI skin, progression maps.",
        [
            "Load and validate Experience Pack manifest",
            "Hot-swap presentation without core fork",
            "Bind copy tables and reading level",
            "Enforce pack cannot override G-rules",
        ],
        [
            "pack.load(pack_id)",
            "pack.getConfig(key)",
            "pack.getCopy(table, key)",
            "pack.validate()",
        ],
        ["pack.loaded", "pack.config_changed"],
        ["engine.initialize"],
        ["Experience Pack manifest", "Fiction manifest refs"],
        ["Active pack context"],
        ["ExperiencePack", "PackManifest"],
        "Unloaded → Validating → Active",
        ["Pack validation ≤200 ms"],
        ["Reading level from pack not hardcoded"],
        ["Swap pack integration test in staging"],
        ["teen_se, adult_support_se schema-only packs"],
        ["Separate DB per pack", "Pack overriding Constitution"],
        ["GDB Appendix C aligned"],
    ),
    _rt(
        "analytics",
        "Analytics Runtime",
        "Privacy-respecting event emission. Anonymised allowlist only.",
        [
            "Subscribe to engine events",
            "Filter through analytics allowlist",
            "Batch and flush with consent gates",
            "No PII in world engine payloads",
        ],
        [
            "analytics.track(event_name, metadata)",
            "analytics.setEnabled(enabled)",
            "analytics.flush()",
        ],
        ["analytics.flushed"],
        ["interaction.completed", "world.loaded", "progression.node_unlocked"],
        ["Allowlist config", "Consent state"],
        ["Event buffer"],
        ["AnalyticsEvent"],
        "Disabled → Buffering → Flushing",
        ["Analytics ≤1 ms per event", "Async flush"],
        ["No child name in analytics payloads"],
        ["Allowlist contract tests"],
        ["New events via allowlist manifest"],
        ["Surveillance metrics", "Sibling comparison events"],
        ["Existing analytics-shim allowlist pattern"],
    ),
    _rt(
        "accessibility",
        "Accessibility Runtime",
        "Central a11y prefs: reduced motion, mute, touch size, contrast hints.",
        [
            "Read system prefs on boot",
            "Propagate flags to all runtimes",
            "Enforce 48 px touch (Design System / GDB Appendix H)",
            "Validate contrast hints for parent surfaces",
        ],
        [
            "a11y.getPref(key)",
            "a11y.setPref(key, value)",
            "a11y.applySystemPrefs()",
        ],
        ["a11y.pref_changed"],
        ["engine.ready"],
        ["OS accessibility settings", "Pack a11y overrides"],
        ["Preference store"],
        ["AccessibilityPrefs"],
        "Init → Active",
        ["Pref propagation ≤1 ms at boot"],
        ["Full completion path silent + reduced motion"],
        ["Regression checklist Appendix H equivalent"],
        ["New prefs via manifest registry"],
        ["a11y as afterthought per feature"],
        ["GDB Appendix H pass"],
    ),
    _rt(
        "performance",
        "Performance Runtime",
        "FPS monitor, tier detection, dynamic quality, battery awareness.",
        [
            "Track frame time and FPS",
            "Assign device tier (low/mid/high)",
            "Downgrade particles, physics, ambient sim under budget",
            "Report budgets to Developer Runtime",
        ],
        [
            "perf.getTier()",
            "perf.getFrameMetrics()",
            "perf.setQualityLevel(level)",
        ],
        ["perf.tier_changed", "perf.budget_exceeded"],
        ["engine.tick"],
        ["Device profile", "Thermal state if available"],
        ["Rolling frame metrics"],
        ["PerformanceProfile"],
        "Monitoring → Throttling → Recovering",
        ["Target 60 FPS — 99.9% mobile users", "Degrade gracefully before drop"],
        ["Never remove a11y paths when throttling"],
        ["Soak tests on iPhone + mid Android", "Battery drain profile"],
        ["Custom tiers via manifest"],
        ["Desktop-only optimization", "Silent thermal throttle breaking input"],
        ["Mobile-first budgets documented"],
    ),
    _rt(
        "developer",
        "Developer Runtime",
        "Debug overlays, manifest hot reload (dev only), runtime inspectors.",
        [
            "Expose runtime state inspectors",
            "Validate manifests in CI",
            "Visualize graphs (scene, interaction, progression)",
            "Never ship enabled in child release builds",
        ],
        [
            "dev.inspect(runtime_name)",
            "dev.validateManifest(path)",
            "dev.visualizeGraph(graph_type, id)",
        ],
        ["dev.validation_failed"],
        ["engine.ready"],
        ["Dev build flag"],
        ["Inspector state"],
        ["DevToolsConfig"],
        "Disabled → Active (dev builds only)",
        ["Zero overhead when disabled"],
        ["N/A in release child builds"],
        ["Manifest validation in CI gate"],
        ["Plugin debug panels"],
        ["Dev tools in release child app"],
        ["Stripped from release binary"],
    ),
    _rt(
        "testing",
        "Testing Runtime",
        "Headless simulation, deterministic replay, contract test hooks.",
        [
            "Deterministic tick with fixed seed",
            "Inject input sequences for gesture tests",
            "Snapshot graph state for regression",
            "Integrate with CI gate",
        ],
        [
            "test.runScenario(scenario_id)",
            "test.injectInput(sequence)",
            "test.snapshot(scope)",
            "test.assertEvent(event_name, payload_matcher)",
        ],
        ["test.scenario_completed", "test.assertion_failed"],
        ["engine.tick"],
        ["Test scenario manifest"],
        ["Replay log"],
        ["TestScenario", "ReplayLog"],
        "Idle → Running → Passed/Failed",
        ["Headless scenario ≤30 s each"],
        ["Test reduced motion paths explicitly"],
        ["Scenario library per world", "Contract tests for all schemas"],
        ["Fuzz interaction graphs"],
        ["Non-deterministic tests for core loop"],
        ["test:gate integration"],
    ),
]
