'use strict';

/**
 * Minnesrummet — allowlist migration TEMPLATE (BL-044).
 *
 * NO family is seeded. This migration is a documented no-op placeholder.
 * When HAG approves QA allowlist, create a NEW migration (do not edit this file)
 * following the pattern in the comment block below.
 *
 * Pattern reference: migrations/1809150000000_garden_playable_allowlist.js
 */

module.exports = {
  name: '1809520000000_memory_hall_allowlist_template',

  up: async (_client) => {
    // Intentionally empty — template only.
    // HAG required before any family_features row for memory_hall_playable.
    //
    // Approved allowlist example (NEW migration file):
    //
    // await client.query(
    //   `INSERT INTO family_features (family_id, feature_slug)
    //    SELECT DISTINCT p.family_id, 'memory_hall_playable'
    //    FROM parent p
    //    JOIN family f ON f.id = p.family_id
    //    WHERE LOWER(p.email) = LOWER($1)
    //      AND f.archived_at IS NULL
    //    ON CONFLICT (family_id, feature_slug) DO NOTHING`,
    //   ['qa-family@example.com']
    // );
  },

  down: async (_client) => {
    // No-op — nothing seeded in up().
  },
};
