'use strict';

/** @readonly */
const ReasonCode = {
  NO_CHILD_LOGIN: 'NO_CHILD_LOGIN',
  WAITING_FOR_PARENT_ACK: 'WAITING_FOR_PARENT_ACK',
  READY_FOR_HANDOFF: 'READY_FOR_HANDOFF',
  FIRST_SUCCESS_COMPLETED: 'FIRST_SUCCESS_COMPLETED',
  INCONSISTENT_STATE: 'INCONSISTENT_STATE',
  PHASE_SETTING_UP: 'PHASE_SETTING_UP',
  AWAITING_FIRST_COMPLETION: 'AWAITING_FIRST_COMPLETION',
  COACH_CONSISTENCY: 'COACH_CONSISTENCY',
  COACH_EVENING: 'COACH_EVENING',
  EXPANDING_HANDOFF: 'EXPANDING_HANDOFF',
  ESTABLISHED_ROUTINE: 'ESTABLISHED_ROUTINE',
  INDEPENDENCE_ACHIEVED: 'INDEPENDENCE_ACHIEVED',
  PEDAGOG_SKIP: 'PEDAGOG_SKIP',
};

module.exports = { ReasonCode };
