"""Parent Experience Scenarios — concrete family situations."""

SCENARIOS = [
    {
        "id": "SC-01",
        "name": "Trött ensamförälder",
        "context": "Jobbar sent; morgon kaos ensam med två barn",
        "parent_need": "SHARE_RESPONSIBILITY senare; nu SHOW_CHILD + COMPLETE_DAY",
        "product": "Dag 0 färdig — noll setup. Ett coach-kort. Handoff på 30 sek.",
        "coach": "Tyst efter rutin flyter. INVITE_PARENT först vecka 2 om need kvar",
        "avoid": "Admin-dashboard, kvälls-push, skuld vid miss",
        "success_signal": "Förälder rapporterar färre upprepningar; sover bättre onsdag",
    },
    {
        "id": "SC-02",
        "name": "Två föräldrar i samma hem",
        "context": "Båda vuxna närvarande; delad ansvarskänsla",
        "parent_need": "Samma sanning, ingen 'vem gjorde fel'",
        "product": "Real-time sync node/rutin-state. Neutral progress view",
        "coach": "INVITE_PARENT om en bär allt; annars tyst",
        "avoid": "Leaderboard, tilldelning av skuld",
        "success_signal": "Båda ser stolthet; ingen nagging via app",
    },
    {
        "id": "SC-03",
        "name": "Separerade föräldrar",
        "context": "Två hushåll; barn växlar",
        "parent_need": "Koordinering utan konflikt i appen",
        "product": "Co-parent invite; samma barnschema synkat; neutral copy",
        "coach": "SHARE_RESPONSIBILITY; aldrig 'den andra föräldern missade'",
        "avoid": "Jämförelse vem loggat in; meddelanden som eskalerar",
        "success_signal": "Barn upplever samma rutin i båda hem",
    },
    {
        "id": "SC-04",
        "name": "Bonusfamilj",
        "context": "Styvpappa/mamma; känslig inkludering",
        "parent_need": "Relatedness utan att trampa primär förälder",
        "product": "Roller primary/shared; Familj-värld relatedness; invite optional",
        "coach": "Ingen 'bjud in bonus' default — parent initierar",
        "avoid": "Copy som antar kärnfamilj; övervakning av 'rätt' förälder",
        "success_signal": "Bonusförälder känner sig medspelare, inte gäst-admin",
    },
    {
        "id": "SC-05",
        "name": "Barn med ADHD",
        "context": "Exekutiv funktion; impuls; behov av tydlighet",
        "parent_need": "Mindre mental load — inte fler regler",
        "product": "NOW/NEXT/LATER; ett steg; visuellt först; OT-aligned 48 px",
        "coach": "PERSONALIZE rutin långsamt — aldrig 'fixa barnet'",
        "avoid": "Skuld vid ofullständig dag; timer-panic",
        "success_signal": "Barn startar själv ett steg; förälder slutar micro-manage",
    },
    {
        "id": "SC-06",
        "name": "Barn med autism",
        "context": "Predictability; sensorisk känslighet",
        "parent_need": "Stabil sekvens; förutsägbar celebration",
        "product": "Reduced motion respekterat; ljud av; samma ordning varje dag",
        "coach": "Calm tone; inga överraskningar utan förberedelse",
        "avoid": "Micro-events som stör; plötslig schemaändring",
        "success_signal": "Barn frågar själv om Idag; meltdown minskar i övergång",
    },
    {
        "id": "SC-07",
        "name": "Familj som slutar använda appen",
        "context": "30+ dagar dormant; livet tog över",
        "parent_need": "Dignity vid återkomst eller avslut",
        "product": "Ingen skuld-push. Data kvar. Vacation/dormant state",
        "coach": "RE_ENGAGE endast vid öppning — inte email-bomb",
        "avoid": "'Du har missat 34 dagar'",
        "success_signal": "Öppnar igen utan skam; eller avslutar med goodwill",
    },
    {
        "id": "SC-08",
        "name": "Familj som kommer tillbaka efter 30 dagar",
        "context": "Semester/sjukdom/kaos — nu vill de prova igen",
        "parent_need": "Enkel restart",
        "product": "Recovery mode: 'Fortsätt där ni var' — rutin intakt, värld välkomnande",
        "coach": "RESUME_ROUTINE; encouragement; inget catch-up marathon",
        "avoid": "Kräva re-onboarding wizard",
        "success_signal": "First completion inom 48 h efter återkomst",
    },
]
